#include "genesis/cognition/affect_persistence.hpp"
#include "genesis/runtime/runtime.hpp"
#include <bit>
#include <cctype>
#include <fstream>
#include <iterator>
#include <stdexcept>
namespace genesis::cognition {namespace {
constexpr std::string_view magic="GENESIS-AFFECT";constexpr std::uint64_t schema=1,max_items=1000000,max_field=16U*1024U*1024U;
void err(AffectStoreError*e,AffectStoreErrorCode c,std::string m){if(e){e->code=c;e->message=std::move(m);}}void idok(std::string_view s){if(s.empty()||s.size()>128||s=="."||s=="..")throw std::invalid_argument("unsafe identifier");for(unsigned char c:s)if(!std::isalnum(c)&&c!='_'&&c!='-'&&c!='.')throw std::invalid_argument("unsafe identifier character");}void u64(std::string&o,std::uint64_t v){for(unsigned s=0;s<64;s+=8)o.push_back(static_cast<char>((v>>s)&255));}std::uint64_t get64(std::string_view b,std::size_t&o){if(o>b.size()||b.size()-o<8)throw std::runtime_error("truncated integer");std::uint64_t v=0;for(unsigned s=0;s<64;s+=8)v|=static_cast<std::uint64_t>(static_cast<unsigned char>(b[o++]))<<s;return v;}void str(std::string&o,std::string_view s){u64(o,s.size());o.append(s);}std::string getstr(std::string_view b,std::size_t&o){const auto n=get64(b,o);if(n>max_field||n>b.size()-o)throw std::runtime_error("invalid field length");std::string s(b.substr(o,n));o+=n;return s;}void state(std::string&o,const AffectState&s){u64(o,std::bit_cast<std::uint64_t>(s.valence));u64(o,std::bit_cast<std::uint64_t>(s.arousal));u64(o,std::bit_cast<std::uint64_t>(s.stress));u64(o,std::bit_cast<std::uint64_t>(s.regulation_load));u64(o,s.updated_at);}AffectState getstate(std::string_view b,std::size_t&o){return {std::bit_cast<double>(get64(b,o)),std::bit_cast<double>(get64(b,o)),std::bit_cast<double>(get64(b,o)),std::bit_cast<double>(get64(b,o)),get64(b,o)};}std::string readall(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("cannot open affect record");std::string b{std::istreambuf_iterator<char>(f),{}};if(f.bad())throw std::runtime_error("cannot read affect record");return b;}
}
AffectStore::AffectStore(std::filesystem::path root,std::size_t maximum):root_(std::move(root)),maximum_record_bytes_(maximum){if(root_.empty()||maximum<1024)throw std::invalid_argument("invalid affect store configuration");}
std::string AffectStore::serialize(const AffectRegulator&m){if(!m.verify())throw std::invalid_argument("invalid affect model");std::string o(magic);u64(o,schema);str(o,m.organism_id_);u64(o,m.signal_capacity_);u64(o,m.regulation_capacity_);state(o,m.state_);u64(o,m.signals_.size());for(const auto&s:m.signals_){str(o,s.id);str(o,s.source_id);str(o,s.evidence_digest);u64(o,static_cast<std::uint64_t>(s.source));u64(o,std::bit_cast<std::uint64_t>(s.valence));u64(o,std::bit_cast<std::uint64_t>(s.arousal));u64(o,std::bit_cast<std::uint64_t>(s.stress));u64(o,std::bit_cast<std::uint64_t>(s.confidence));u64(o,s.observed_at);}u64(o,m.regulations_.size());for(const auto&r:m.regulations_){str(o,r.id);str(o,r.evidence_digest);u64(o,static_cast<std::uint64_t>(r.kind));u64(o,std::bit_cast<std::uint64_t>(r.intensity));u64(o,r.applied_at);state(o,r.before);state(o,r.after);}o+=runtime::sha256(o);return o;}
std::optional<AffectRegulator> AffectStore::deserialize(std::string_view b,AffectStoreError*e){try{if(b.size()<magic.size()+8+64||b.substr(0,magic.size())!=magic)throw std::runtime_error("invalid affect magic");const auto payload=b.substr(0,b.size()-64);if(runtime::sha256(payload)!=b.substr(b.size()-64))throw std::runtime_error("affect checksum mismatch");std::size_t o=magic.size();if(get64(payload,o)!=schema){err(e,AffectStoreErrorCode::unsupported_schema,"unsupported affect schema");return std::nullopt;}auto owner=getstr(payload,o);const auto sc=get64(payload,o),rc=get64(payload,o);if(!sc||!rc||sc>max_items||rc>max_items)throw std::runtime_error("invalid affect capacities");AffectRegulator m(owner,sc,rc);m.state_=getstate(payload,o);const auto signals=get64(payload,o);if(signals>sc)throw std::runtime_error("signal count exceeds capacity");for(std::uint64_t n=0;n<signals;++n){AffectSignal s;s.id=getstr(payload,o);s.source_id=getstr(payload,o);s.evidence_digest=getstr(payload,o);const auto source=get64(payload,o);if(source>static_cast<std::uint64_t>(AffectSource::operator_input))throw std::runtime_error("invalid affect source");s.source=static_cast<AffectSource>(source);s.valence=std::bit_cast<double>(get64(payload,o));s.arousal=std::bit_cast<double>(get64(payload,o));s.stress=std::bit_cast<double>(get64(payload,o));s.confidence=std::bit_cast<double>(get64(payload,o));s.observed_at=get64(payload,o);m.signals_.push_back(std::move(s));}const auto regulations=get64(payload,o);if(regulations>rc)throw std::runtime_error("regulation count exceeds capacity");for(std::uint64_t n=0;n<regulations;++n){RegulationRecord r;r.id=getstr(payload,o);r.evidence_digest=getstr(payload,o);const auto kind=get64(payload,o);if(kind>static_cast<std::uint64_t>(RegulationKind::operator_support))throw std::runtime_error("invalid regulation kind");r.kind=static_cast<RegulationKind>(kind);r.intensity=std::bit_cast<double>(get64(payload,o));r.applied_at=get64(payload,o);r.before=getstate(payload,o);r.after=getstate(payload,o);m.regulations_.push_back(std::move(r));}if(o!=payload.size()||!m.verify())throw std::runtime_error("trailing or invalid affect data");err(e,AffectStoreErrorCode::none,{});return m;}catch(const std::exception&x){err(e,AffectStoreErrorCode::corrupt_record,x.what());return std::nullopt;}}
bool AffectStore::write(const AffectRegulator&m,std::string_view version,AffectStoreError*e)const{try{idok(m.organism_id());idok(version);auto bytes=serialize(m);if(bytes.size()>maximum_record_bytes_)throw std::invalid_argument("affect record exceeds configured limit");std::error_code ec;std::filesystem::create_directories(root_,ec);if(ec)throw std::runtime_error("cannot create affect store");const auto target=root_/(m.organism_id()+"."+std::string(version)+".affect");if(std::filesystem::exists(target)){if(readall(target)==bytes){err(e,AffectStoreErrorCode::none,{});return true;}err(e,AffectStoreErrorCode::conflicting_version,"immutable affect version conflict");return false;}const auto temp=std::filesystem::path(target.string()+".tmp-"+runtime::sha256(bytes));{std::ofstream f(temp,std::ios::binary|std::ios::trunc);f.write(bytes.data(),static_cast<std::streamsize>(bytes.size()));f.flush();if(!f)throw std::runtime_error("cannot flush affect record");}std::filesystem::rename(temp,target,ec);if(ec){std::filesystem::remove(temp);throw std::runtime_error("cannot atomically commit affect record");}err(e,AffectStoreErrorCode::none,{});return true;}catch(const std::invalid_argument&x){err(e,AffectStoreErrorCode::invalid_model,x.what());return false;}catch(const std::exception&x){err(e,AffectStoreErrorCode::io_error,x.what());return false;}}
std::optional<AffectRegulator> AffectStore::read(std::string_view owner,std::string_view version,AffectStoreError*e)const{try{idok(owner);idok(version);const auto path=root_/(std::string(owner)+"."+std::string(version)+".affect");if(!std::filesystem::exists(path)){err(e,AffectStoreErrorCode::not_found,"affect record not found");return std::nullopt;}const auto bytes=readall(path);if(bytes.size()>maximum_record_bytes_){err(e,AffectStoreErrorCode::corrupt_record,"affect record exceeds configured limit");return std::nullopt;}auto m=deserialize(bytes,e);if(m&&m->organism_id()!=owner){err(e,AffectStoreErrorCode::corrupt_record,"affect owner mismatch");return std::nullopt;}return m;}catch(const std::invalid_argument&x){err(e,AffectStoreErrorCode::invalid_identifier,x.what());return std::nullopt;}catch(const std::exception&x){err(e,AffectStoreErrorCode::io_error,x.what());return std::nullopt;}}
}
