#include "genesis/cognition/affect.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <stdexcept>
#include <set>
namespace genesis::cognition {namespace {bool text(std::string_view s){return !s.empty()&&s.size()<=1024&&std::all_of(s.begin(),s.end(),[](unsigned char c){return c>=0x20&&c!=0x7f;});}bool digest(std::string_view s){return s.size()==64&&std::all_of(s.begin(),s.end(),[](unsigned char c){return std::isxdigit(c)!=0;});}bool ratio(double v){return std::isfinite(v)&&v>=0&&v<=1;}bool valence(double v){return std::isfinite(v)&&v>=-1&&v<=1;}void fail(std::string*e,const char*m){if(e)*e=m;} }
AffectRegulator::AffectRegulator(std::string owner,std::size_t sc,std::size_t rc):organism_id_(std::move(owner)),signal_capacity_(sc),regulation_capacity_(rc){if(!text(organism_id_)||!sc||!rc)throw std::invalid_argument("invalid affect configuration");signals_.reserve(sc);regulations_.reserve(rc);}
bool AffectRegulator::ingest(AffectSignal s,std::string*e){if(e)e->clear();if(signals_.size()>=signal_capacity_||!text(s.id)||!text(s.source_id)||!digest(s.evidence_digest)||!valence(s.valence)||!ratio(s.arousal)||!ratio(s.stress)||!ratio(s.confidence)||s.observed_at<state_.updated_at||static_cast<unsigned>(s.source)>static_cast<unsigned>(AffectSource::operator_input)||std::any_of(signals_.begin(),signals_.end(),[&](const auto&x){return x.id==s.id;})){fail(e,"invalid duplicate or over-capacity affect signal");return false;}const double weight=s.confidence;state_.valence=std::clamp(state_.valence*(1-weight)+s.valence*weight,-1.0,1.0);state_.arousal=std::clamp(state_.arousal*(1-weight)+s.arousal*weight,0.0,1.0);state_.stress=std::clamp(state_.stress*(1-weight)+s.stress*weight,0.0,1.0);state_.updated_at=s.observed_at;signals_.push_back(std::move(s));return true;}
bool AffectRegulator::ingest_homeostasis(std::string id,organism::Metric metric,organism::HomeostasisDecision d,std::string evidence,std::uint64_t at,std::string*e){if(static_cast<unsigned>(metric)>static_cast<unsigned>(organism::Metric::maintenance_backlog)||static_cast<unsigned>(d.level)>static_cast<unsigned>(organism::PressureLevel::invalid)){fail(e,"invalid homeostasis affect input");return false;}const double severity=d.level==organism::PressureLevel::critical_low||d.level==organism::PressureLevel::critical_high?1.0:d.level==organism::PressureLevel::low_warning||d.level==organism::PressureLevel::high_warning?.6:d.level==organism::PressureLevel::nominal?0.0:.8;return ingest({std::move(id),"homeostasis-"+std::to_string(static_cast<unsigned>(metric)),std::move(evidence),AffectSource::homeostasis,-severity*.4,severity,severity,1,at},e);}
bool AffectRegulator::decay(double amount,std::uint64_t at,std::string*e){if(e)e->clear();if(!ratio(amount)||at<state_.updated_at){fail(e,"invalid affect decay");return false;}const double retain=1-amount;state_.valence*=retain;state_.arousal*=retain;state_.stress*=retain;state_.regulation_load*=retain;state_.updated_at=at;return true;}
bool AffectRegulator::regulate(std::string id,RegulationKind kind,double intensity,std::string evidence,std::uint64_t at,std::string*e){if(e)e->clear();if(regulations_.size()>=regulation_capacity_||!text(id)||!digest(evidence)||!ratio(intensity)||at<state_.updated_at||static_cast<unsigned>(kind)>static_cast<unsigned>(RegulationKind::operator_support)||std::any_of(regulations_.begin(),regulations_.end(),[&](const auto&x){return x.id==id;})){fail(e,"invalid duplicate or over-capacity affect regulation");return false;}const auto before=state_;switch(kind){case RegulationKind::reappraisal:state_.valence=std::clamp(state_.valence+intensity*.3,-1.0,1.0);state_.stress=std::clamp(state_.stress-intensity*.2,0.0,1.0);break;case RegulationKind::calming:state_.arousal=std::clamp(state_.arousal-intensity*.5,0.0,1.0);state_.stress=std::clamp(state_.stress-intensity*.4,0.0,1.0);break;case RegulationKind::grounding:state_.arousal=std::clamp(state_.arousal-intensity*.3,0.0,1.0);state_.stress=std::clamp(state_.stress-intensity*.3,0.0,1.0);break;case RegulationKind::operator_support:state_.stress=std::clamp(state_.stress-intensity*.5,0.0,1.0);break;}state_.regulation_load=std::clamp(state_.regulation_load+intensity*.2,0.0,1.0);state_.updated_at=at;regulations_.push_back({std::move(id),std::move(evidence),kind,intensity,at,before,state_});return true;}
AffectInfluence AffectRegulator::influence(const WorkspaceItem&i,double mv)const{AffectInfluence out{i,1,false};if(!valence(mv))return out;const double congruence=1-std::abs(state_.valence-mv)/2;out.salience_multiplier=std::clamp(.75+congruence*.5+state_.arousal*.25,0.5,1.5);out.item.salience=std::clamp(i.salience*out.salience_multiplier,0.0,1.0);return out;}
bool AffectRegulator::verify()const{if(!text(organism_id_)||signals_.size()>signal_capacity_||regulations_.size()>regulation_capacity_||!valence(state_.valence)||!ratio(state_.arousal)||!ratio(state_.stress)||!ratio(state_.regulation_load))return false;std::uint64_t time=0,regulation_time=0;std::set<std::string> signal_ids,regulation_ids;for(const auto&s:signals_){if(!signal_ids.insert(s.id).second||!text(s.id)||!text(s.source_id)||!digest(s.evidence_digest)||static_cast<unsigned>(s.source)>static_cast<unsigned>(AffectSource::operator_input)||!valence(s.valence)||!ratio(s.arousal)||!ratio(s.stress)||!ratio(s.confidence)||s.observed_at<time||s.observed_at>state_.updated_at)return false;time=s.observed_at;}for(const auto&r:regulations_){if(!regulation_ids.insert(r.id).second||!text(r.id)||!digest(r.evidence_digest)||static_cast<unsigned>(r.kind)>static_cast<unsigned>(RegulationKind::operator_support)||!ratio(r.intensity)||!valence(r.before.valence)||!valence(r.after.valence)||!ratio(r.before.arousal)||!ratio(r.after.arousal)||!ratio(r.before.stress)||!ratio(r.after.stress)||!ratio(r.before.regulation_load)||!ratio(r.after.regulation_load)||r.applied_at<regulation_time||r.after.updated_at!=r.applied_at||r.applied_at>state_.updated_at)return false;regulation_time=r.applied_at;}return true;}
}
