#include "genesis/cognition/capability_persistence.hpp"
#include "genesis/runtime/runtime.hpp"
#include <bit>
#include <cctype>
#include <fstream>
#include <iterator>
#include <stdexcept>
namespace genesis::cognition {namespace {
constexpr std::string_view magic="GENESIS-CAPABILITY";constexpr std::uint64_t schema=1,max_items=1000000,max_field=16U*1024U*1024U;
void err(CapabilityStoreError*e,CapabilityStoreErrorCode c,std::string m){if(e){e->code=c;e->message=std::move(m);}}void idok(std::string_view s){if(s.empty()||s.size()>128||s=="."||s=="..")throw std::invalid_argument("unsafe identifier");for(unsigned char c:s)if(!std::isalnum(c)&&c!='_'&&c!='-'&&c!='.')throw std::invalid_argument("unsafe identifier character");}void u64(std::string&o,std::uint64_t v){for(unsigned s=0;s<64;s+=8)o.push_back(static_cast<char>((v>>s)&255));}std::uint64_t get64(std::string_view b,std::size_t&o){if(o>b.size()||b.size()-o<8)throw std::runtime_error("truncated integer");std::uint64_t v=0;for(unsigned s=0;s<64;s+=8)v|=static_cast<std::uint64_t>(static_cast<unsigned char>(b[o++]))<<s;return v;}void str(std::string&o,std::string_view s){u64(o,s.size());o.append(s);}std::string getstr(std::string_view b,std::size_t&o){const auto n=get64(b,o);if(n>max_field||n>b.size()-o)throw std::runtime_error("invalid field length");std::string s(b.substr(o,n));o+=n;return s;}std::string readall(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("cannot open capability record");std::string b{std::istreambuf_iterator<char>(f),{}};if(f.bad())throw std::runtime_error("cannot read capability record");return b;}
}
CapabilityStore::CapabilityStore(std::filesystem::path root,std::size_t maximum):root_(std::move(root)),maximum_record_bytes_(maximum){if(root_.empty()||maximum<1024)throw std::invalid_argument("invalid capability store configuration");}
std::string CapabilityStore::serialize(const SelfCapabilityModel&m){if(!m.verify())throw std::invalid_argument("invalid capability model");std::string o(magic);u64(o,schema);str(o,m.organism_id());u64(o,m.capacity());u64(o,m.policy().minimum_trials);u64(o,std::bit_cast<std::uint64_t>(m.policy().minimum_success_rate));u64(o,m.policy().maximum_consecutive_failures);u64(o,m.records().size());for(const auto&[_,r]:m.records()){str(o,r.id);str(o,r.route);str(o,r.declaration_evidence_digest);str(o,r.latest_evidence_digest);str(o,r.qualification_evidence_digest);u64(o,static_cast<std::uint64_t>(r.level));u64(o,r.trials);u64(o,r.successes);u64(o,r.consecutive_failures);u64(o,r.updated_at);u64(o,std::bit_cast<std::uint64_t>(r.calibrated_competence));u64(o,r.revoked);}o+=runtime::sha256(o);return o;}
std::optional<SelfCapabilityModel> CapabilityStore::deserialize(std::string_view b,CapabilityStoreError*e){try{if(b.size()<magic.size()+8+64||b.substr(0,magic.size())!=magic)throw std::runtime_error("invalid capability magic");const auto payload=b.substr(0,b.size()-64);if(runtime::sha256(payload)!=b.substr(b.size()-64))throw std::runtime_error("capability checksum mismatch");std::size_t o=magic.size();if(get64(payload,o)!=schema){err(e,CapabilityStoreErrorCode::unsupported_schema,"unsupported capability schema");return std::nullopt;}auto owner=getstr(payload,o);const auto capacity=get64(payload,o);CompetencyPolicy policy{get64(payload,o),std::bit_cast<double>(get64(payload,o)),get64(payload,o)};const auto count=get64(payload,o);if(!capacity||capacity>max_items||count>capacity)throw std::runtime_error("invalid capability capacity");SelfCapabilityModel model(owner,capacity,policy);for(std::uint64_t i=0;i<count;++i){CapabilityRecord r;r.id=getstr(payload,o);r.route=getstr(payload,o);r.declaration_evidence_digest=getstr(payload,o);r.latest_evidence_digest=getstr(payload,o);r.qualification_evidence_digest=getstr(payload,o);const auto level=get64(payload,o);if(level>static_cast<std::uint64_t>(CapabilityEvidenceLevel::qualified)||model.records_.contains(r.id))throw std::runtime_error("invalid capability enum or duplicate");r.level=static_cast<CapabilityEvidenceLevel>(level);r.trials=get64(payload,o);r.successes=get64(payload,o);r.consecutive_failures=get64(payload,o);r.updated_at=get64(payload,o);r.calibrated_competence=std::bit_cast<double>(get64(payload,o));r.revoked=get64(payload,o)!=0;model.records_.emplace(r.id,std::move(r));}if(o!=payload.size()||!model.verify())throw std::runtime_error("trailing or invalid capability data");err(e,CapabilityStoreErrorCode::none,{});return model;}catch(const std::exception&x){err(e,CapabilityStoreErrorCode::corrupt_record,x.what());return std::nullopt;}}
bool CapabilityStore::write(const SelfCapabilityModel&m,std::string_view version,CapabilityStoreError*e)const{try{idok(m.organism_id());idok(version);auto bytes=serialize(m);if(bytes.size()>maximum_record_bytes_)throw std::invalid_argument("capability record exceeds configured limit");std::error_code ec;std::filesystem::create_directories(root_,ec);if(ec)throw std::runtime_error("cannot create capability store");const auto target=root_/(m.organism_id()+"."+std::string(version)+".capability");if(std::filesystem::exists(target)){if(readall(target)==bytes){err(e,CapabilityStoreErrorCode::none,{});return true;}err(e,CapabilityStoreErrorCode::conflicting_version,"immutable capability version conflict");return false;}const auto temp=std::filesystem::path(target.string()+".tmp-"+runtime::sha256(bytes));{std::ofstream f(temp,std::ios::binary|std::ios::trunc);f.write(bytes.data(),static_cast<std::streamsize>(bytes.size()));f.flush();if(!f)throw std::runtime_error("cannot flush capability record");}std::filesystem::rename(temp,target,ec);if(ec){std::filesystem::remove(temp);throw std::runtime_error("cannot atomically commit capability record");}err(e,CapabilityStoreErrorCode::none,{});return true;}catch(const std::invalid_argument&x){err(e,CapabilityStoreErrorCode::invalid_model,x.what());return false;}catch(const std::exception&x){err(e,CapabilityStoreErrorCode::io_error,x.what());return false;}}
std::optional<SelfCapabilityModel> CapabilityStore::read(std::string_view owner,std::string_view version,CapabilityStoreError*e)const{try{idok(owner);idok(version);const auto path=root_/(std::string(owner)+"."+std::string(version)+".capability");if(!std::filesystem::exists(path)){err(e,CapabilityStoreErrorCode::not_found,"capability record not found");return std::nullopt;}const auto bytes=readall(path);if(bytes.size()>maximum_record_bytes_){err(e,CapabilityStoreErrorCode::corrupt_record,"capability record exceeds configured limit");return std::nullopt;}auto model=deserialize(bytes,e);if(model&&model->organism_id()!=owner){err(e,CapabilityStoreErrorCode::corrupt_record,"capability owner mismatch");return std::nullopt;}return model;}catch(const std::invalid_argument&x){err(e,CapabilityStoreErrorCode::invalid_identifier,x.what());return std::nullopt;}catch(const std::exception&x){err(e,CapabilityStoreErrorCode::io_error,x.what());return std::nullopt;}}
}
