#include "genesis/cognition/capability.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <limits>
#include <stdexcept>
namespace genesis::cognition {namespace {bool text(std::string_view s){return !s.empty()&&s.size()<=1024&&std::all_of(s.begin(),s.end(),[](unsigned char c){return c>=0x20&&c!=0x7f;});}bool digest(std::string_view s){return s.size()==64&&std::all_of(s.begin(),s.end(),[](unsigned char c){return std::isxdigit(c)!=0;});}bool ratio(double v){return std::isfinite(v)&&v>=0&&v<=1;}void fail(std::string*e,const char*m){if(e)*e=m;}}
SelfCapabilityModel::SelfCapabilityModel(std::string owner,std::size_t capacity,CompetencyPolicy policy):organism_id_(std::move(owner)),capacity_(capacity),policy_(policy){if(!text(organism_id_)||!capacity_||!policy_.minimum_trials||!ratio(policy_.minimum_success_rate)||!policy_.maximum_consecutive_failures)throw std::invalid_argument("invalid capability model configuration");}
bool SelfCapabilityModel::declare_capability(std::string id,std::string route,std::string evidence,std::uint64_t at,std::string*e){if(e)e->clear();if(records_.size()>=capacity_||!text(id)||!text(route)||!digest(evidence)||records_.contains(id)){fail(e,"invalid duplicate or over-capacity capability declaration");return false;}records_.emplace(id,CapabilityRecord{id,std::move(route),evidence,evidence,{},CapabilityEvidenceLevel::declared,0,0,0,at,0,false});return true;}
bool SelfCapabilityModel::record_outcome(std::string_view id,bool success,std::string_view evidence,std::uint64_t at,std::string*e){if(e)e->clear();auto it=records_.find(std::string(id));if(it==records_.end()||it->second.revoked||!digest(evidence)||at<it->second.updated_at||it->second.trials==std::numeric_limits<std::uint64_t>::max()||(success&&it->second.successes==std::numeric_limits<std::uint64_t>::max())||(!success&&it->second.consecutive_failures==std::numeric_limits<std::uint64_t>::max())){fail(e,"invalid capability outcome");return false;}auto&r=it->second;++r.trials;if(success){++r.successes;r.consecutive_failures=0;}else ++r.consecutive_failures;r.calibrated_competence=static_cast<double>(r.successes)/static_cast<double>(r.trials);r.latest_evidence_digest=std::string(evidence);r.updated_at=at;if(r.level==CapabilityEvidenceLevel::declared)r.level=CapabilityEvidenceLevel::observed;if(r.level==CapabilityEvidenceLevel::qualified&&r.consecutive_failures>policy_.maximum_consecutive_failures){r.level=CapabilityEvidenceLevel::observed;r.qualification_evidence_digest.clear();}return true;}
bool SelfCapabilityModel::qualify(std::string_view id,std::string_view evidence,std::uint64_t at,std::string*e){if(e)e->clear();auto it=records_.find(std::string(id));if(it==records_.end()||it->second.revoked||!digest(evidence)||at<it->second.updated_at||it->second.level!=CapabilityEvidenceLevel::observed||it->second.trials<policy_.minimum_trials||it->second.calibrated_competence<policy_.minimum_success_rate||it->second.consecutive_failures>policy_.maximum_consecutive_failures){fail(e,"capability lacks qualification evidence or competency");return false;}it->second.level=CapabilityEvidenceLevel::qualified;it->second.qualification_evidence_digest=std::string(evidence);it->second.latest_evidence_digest=std::string(evidence);it->second.updated_at=at;return true;}
bool SelfCapabilityModel::revoke(std::string_view id,std::string_view evidence,std::uint64_t at,std::string*e){if(e)e->clear();auto it=records_.find(std::string(id));if(it==records_.end()||it->second.revoked||!digest(evidence)||at<it->second.updated_at){fail(e,"invalid capability revocation");return false;}it->second.revoked=true;it->second.level=CapabilityEvidenceLevel::unavailable;it->second.latest_evidence_digest=std::string(evidence);it->second.qualification_evidence_digest.clear();it->second.updated_at=at;return true;}
bool SelfCapabilityModel::may_execute(std::string_view id,const AuthorizationDecision&a)const noexcept{const auto*r=find(id);return r&&!r->revoked&&r->level==CapabilityEvidenceLevel::qualified&&a.identity_authenticated&&a.policy_allowed&&a.safety_allowed&&digest(a.decision_evidence_digest);}
const CapabilityRecord* SelfCapabilityModel::find(std::string_view id)const noexcept{const auto it=records_.find(std::string(id));return it==records_.end()?nullptr:&it->second;}
bool SelfCapabilityModel::verify()const{if(!text(organism_id_)||!capacity_||records_.size()>capacity_||!policy_.minimum_trials||!ratio(policy_.minimum_success_rate)||!policy_.maximum_consecutive_failures)return false;for(const auto&[id,r]:records_){if(id!=r.id||!text(r.id)||!text(r.route)||!digest(r.declaration_evidence_digest)||!digest(r.latest_evidence_digest)||r.successes>r.trials||!ratio(r.calibrated_competence)||static_cast<unsigned>(r.level)>static_cast<unsigned>(CapabilityEvidenceLevel::qualified))return false;if(r.trials&&std::abs(r.calibrated_competence-static_cast<double>(r.successes)/static_cast<double>(r.trials))>1e-12)return false;if(!r.trials&&r.calibrated_competence!=0)return false;if(r.level==CapabilityEvidenceLevel::qualified&&(!digest(r.qualification_evidence_digest)||r.trials<policy_.minimum_trials||r.calibrated_competence<policy_.minimum_success_rate))return false;if(r.level!=CapabilityEvidenceLevel::qualified&&!r.qualification_evidence_digest.empty())return false;if(r.revoked&&r.level!=CapabilityEvidenceLevel::unavailable)return false;}return true;}
}
