#include "genesis/cognition/continuity_persistence.hpp"
#include "genesis/runtime/runtime.hpp"
#include <bit>
#include <cctype>
#include <fstream>
#include <iterator>
#include <stdexcept>
namespace genesis::cognition {namespace {
constexpr std::string_view magic="GENESIS-CONTINUITY";constexpr std::uint64_t schema=1,max_items=1000000,max_field=16U*1024U*1024U;
void err(ContinuityStoreError*e,ContinuityStoreErrorCode c,std::string m){if(e){e->code=c;e->message=std::move(m);}}void idok(std::string_view s){if(s.empty()||s.size()>128||s=="."||s=="..")throw std::invalid_argument("unsafe identifier");for(unsigned char c:s)if(!std::isalnum(c)&&c!='_'&&c!='-'&&c!='.')throw std::invalid_argument("unsafe identifier character");}void u64(std::string&o,std::uint64_t v){for(unsigned s=0;s<64;s+=8)o.push_back(static_cast<char>((v>>s)&255));}std::uint64_t get64(std::string_view b,std::size_t&o){if(o>b.size()||b.size()-o<8)throw std::runtime_error("truncated integer");std::uint64_t v=0;for(unsigned s=0;s<64;s+=8)v|=static_cast<std::uint64_t>(static_cast<unsigned char>(b[o++]))<<s;return v;}void str(std::string&o,std::string_view s){u64(o,s.size());o.append(s);}std::string getstr(std::string_view b,std::size_t&o){const auto n=get64(b,o);if(n>max_field||n>b.size()-o)throw std::runtime_error("invalid field length");std::string s(b.substr(o,n));o+=n;return s;}std::string readall(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("cannot open continuity record");std::string b{std::istreambuf_iterator<char>(f),{}};if(f.bad())throw std::runtime_error("cannot read continuity record");return b;}
void identity(std::string&o,const LineageIdentity&i){str(o,i.organism_id);str(o,i.genesis_id);str(o,i.lineage_id);str(o,i.birth_event_id);str(o,i.parent_a_id);str(o,i.parent_b_id);str(o,i.genome_hash);str(o,i.inherited_state_hash);str(o,i.birth_snapshot_hash);str(o,i.identity_seed);str(o,i.lineage_signature);str(o,i.cryptographic_provenance);u64(o,i.generation);u64(o,std::bit_cast<std::uint64_t>(i.birth_timestamp));u64(o,i.ancestor_root_ids.size());for(const auto&x:i.ancestor_root_ids)str(o,x);u64(o,static_cast<std::uint64_t>(i.origin));}
LineageIdentity getidentity(std::string_view b,std::size_t&o){LineageIdentity i;i.organism_id=getstr(b,o);i.genesis_id=getstr(b,o);i.lineage_id=getstr(b,o);i.birth_event_id=getstr(b,o);i.parent_a_id=getstr(b,o);i.parent_b_id=getstr(b,o);i.genome_hash=getstr(b,o);i.inherited_state_hash=getstr(b,o);i.birth_snapshot_hash=getstr(b,o);i.identity_seed=getstr(b,o);i.lineage_signature=getstr(b,o);i.cryptographic_provenance=getstr(b,o);i.generation=get64(b,o);i.birth_timestamp=std::bit_cast<std::int64_t>(get64(b,o));const auto n=get64(b,o);if(n>max_items)throw std::runtime_error("too many ancestors");while(i.ancestor_root_ids.size()<n)i.ancestor_root_ids.push_back(getstr(b,o));const auto origin=get64(b,o);if(origin>static_cast<std::uint64_t>(OriginKind::child))throw std::runtime_error("invalid lineage origin");i.origin=static_cast<OriginKind>(origin);return i;}
}
ContinuityStore::ContinuityStore(std::filesystem::path root,std::size_t maximum):root_(std::move(root)),maximum_record_bytes_(maximum){if(root_.empty()||maximum<1024)throw std::invalid_argument("invalid continuity store configuration");}
std::string ContinuityStore::serialize(const AutobiographicalContinuity&j){if(!j.verify())throw std::invalid_argument("invalid continuity journal");std::string o(magic);u64(o,schema);identity(o,j.identity_);u64(o,static_cast<std::uint64_t>(j.anchor_.origin));str(o,j.anchor_.source_organism_id);str(o,j.anchor_.source_checkpoint_digest);u64(o,j.event_capacity_);u64(o,j.checkpoint_capacity_);u64(o,j.events_.size());for(const auto&x:j.events_){str(o,x.id);str(o,x.memory_id);str(o,x.content_digest);str(o,x.provenance_digest);str(o,x.previous_event_digest);str(o,x.event_digest);u64(o,static_cast<std::uint64_t>(x.memory_origin));u64(o,static_cast<std::uint64_t>(x.scope));u64(o,x.sequence);u64(o,x.logical_time);}u64(o,j.checkpoints_.size());for(const auto&c:j.checkpoints_){str(o,c.id);str(o,c.head_event_digest);str(o,c.checkpoint_digest);u64(o,c.sequence);u64(o,c.logical_time);}o+=runtime::sha256(o);return o;}
std::optional<AutobiographicalContinuity> ContinuityStore::deserialize(std::string_view b,ContinuityStoreError*e){try{if(b.size()<magic.size()+8+64||b.substr(0,magic.size())!=magic)throw std::runtime_error("invalid continuity magic");const auto payload=b.substr(0,b.size()-64);if(runtime::sha256(payload)!=b.substr(b.size()-64))throw std::runtime_error("continuity checksum mismatch");std::size_t o=magic.size();if(get64(payload,o)!=schema){err(e,ContinuityStoreErrorCode::unsupported_schema,"unsupported continuity schema");return std::nullopt;}auto id=getidentity(payload,o);const auto ao=get64(payload,o);if(ao>static_cast<std::uint64_t>(OriginKind::child))throw std::runtime_error("invalid anchor origin");ContinuityAnchor anchor{static_cast<OriginKind>(ao),getstr(payload,o),getstr(payload,o)};const auto ec=get64(payload,o),cc=get64(payload,o);if(!ec||!cc||ec>max_items||cc>max_items)throw std::runtime_error("invalid continuity capacities");AutobiographicalContinuity j(std::move(id),std::move(anchor),ec,cc);const auto events=get64(payload,o);if(events>ec)throw std::runtime_error("event count exceeds capacity");for(std::uint64_t n=0;n<events;++n){LifeEvent x;x.id=getstr(payload,o);x.memory_id=getstr(payload,o);x.content_digest=getstr(payload,o);x.provenance_digest=getstr(payload,o);x.previous_event_digest=getstr(payload,o);x.event_digest=getstr(payload,o);const auto mo=get64(payload,o),scope=get64(payload,o);if(mo>static_cast<std::uint64_t>(memory::Origin::external_source)||scope>static_cast<std::uint64_t>(memory::IdentityScope::external_reference))throw std::runtime_error("invalid event origin");x.memory_origin=static_cast<memory::Origin>(mo);x.scope=static_cast<memory::IdentityScope>(scope);x.sequence=get64(payload,o);x.logical_time=get64(payload,o);j.events_.push_back(std::move(x));}const auto checkpoints=get64(payload,o);if(checkpoints>cc)throw std::runtime_error("checkpoint count exceeds capacity");for(std::uint64_t n=0;n<checkpoints;++n){ContinuityCheckpoint c;c.id=getstr(payload,o);c.head_event_digest=getstr(payload,o);c.checkpoint_digest=getstr(payload,o);c.sequence=get64(payload,o);c.logical_time=get64(payload,o);j.checkpoints_.push_back(std::move(c));}if(o!=payload.size()||!j.verify())throw std::runtime_error("trailing or invalid continuity data");err(e,ContinuityStoreErrorCode::none,{});return j;}catch(const std::exception&x){err(e,ContinuityStoreErrorCode::corrupt_record,x.what());return std::nullopt;}}
bool ContinuityStore::write(const AutobiographicalContinuity&j,std::string_view version,ContinuityStoreError*e)const{try{idok(j.identity().organism_id);idok(version);auto bytes=serialize(j);if(bytes.size()>maximum_record_bytes_)throw std::invalid_argument("continuity record exceeds configured limit");std::error_code ec;std::filesystem::create_directories(root_,ec);if(ec)throw std::runtime_error("cannot create continuity store");const auto target=root_/(j.identity().organism_id+"."+std::string(version)+".continuity");if(std::filesystem::exists(target)){if(readall(target)==bytes){err(e,ContinuityStoreErrorCode::none,{});return true;}err(e,ContinuityStoreErrorCode::conflicting_version,"immutable continuity version conflict");return false;}const auto temp=std::filesystem::path(target.string()+".tmp-"+runtime::sha256(bytes));{std::ofstream f(temp,std::ios::binary|std::ios::trunc);f.write(bytes.data(),static_cast<std::streamsize>(bytes.size()));f.flush();if(!f)throw std::runtime_error("cannot flush continuity record");}std::filesystem::rename(temp,target,ec);if(ec){std::filesystem::remove(temp);throw std::runtime_error("cannot atomically commit continuity record");}err(e,ContinuityStoreErrorCode::none,{});return true;}catch(const std::invalid_argument&x){err(e,ContinuityStoreErrorCode::invalid_journal,x.what());return false;}catch(const std::exception&x){err(e,ContinuityStoreErrorCode::io_error,x.what());return false;}}
std::optional<AutobiographicalContinuity> ContinuityStore::read(std::string_view owner,std::string_view version,ContinuityStoreError*e)const{try{idok(owner);idok(version);const auto path=root_/(std::string(owner)+"."+std::string(version)+".continuity");if(!std::filesystem::exists(path)){err(e,ContinuityStoreErrorCode::not_found,"continuity record not found");return std::nullopt;}const auto bytes=readall(path);if(bytes.size()>maximum_record_bytes_){err(e,ContinuityStoreErrorCode::corrupt_record,"continuity record exceeds configured limit");return std::nullopt;}auto j=deserialize(bytes,e);if(j&&j->identity().organism_id!=owner){err(e,ContinuityStoreErrorCode::corrupt_record,"continuity owner mismatch");return std::nullopt;}return j;}catch(const std::invalid_argument&x){err(e,ContinuityStoreErrorCode::invalid_identifier,x.what());return std::nullopt;}catch(const std::exception&x){err(e,ContinuityStoreErrorCode::io_error,x.what());return std::nullopt;}}
}
