#include "genesis/cognition/continuity.hpp"
#include "genesis/runtime/runtime.hpp"
#include <algorithm>
#include <cctype>
#include <limits>
#include <set>
#include <stdexcept>
namespace genesis::cognition {namespace {bool text(std::string_view s){return !s.empty()&&s.size()<=1024&&std::all_of(s.begin(),s.end(),[](unsigned char c){return c>=0x20&&c!=0x7f;});}bool digest(std::string_view s){return s.size()==64&&std::all_of(s.begin(),s.end(),[](unsigned char c){return std::isxdigit(c)!=0;});}void fail(std::string*e,const char*m){if(e)*e=m;}std::string event_hash(std::string_view owner,const LifeEvent&e){return runtime::sha256("autobiography-v1|"+std::string(owner)+"|"+std::to_string(e.sequence)+"|"+std::to_string(e.logical_time)+"|"+e.id+"|"+e.memory_id+"|"+e.content_digest+"|"+e.provenance_digest+"|"+std::to_string(static_cast<unsigned>(e.memory_origin))+"|"+std::to_string(static_cast<unsigned>(e.scope))+"|"+e.previous_event_digest);} }
AutobiographicalContinuity::AutobiographicalContinuity(LineageIdentity identity,ContinuityAnchor anchor,std::size_t ec,std::size_t cc):identity_(std::move(identity)),anchor_(std::move(anchor)),event_capacity_(ec),checkpoint_capacity_(cc){if(!validate(identity_).empty()||!ec||!cc||anchor_.origin!=identity_.origin)throw std::invalid_argument("invalid continuity configuration");if(anchor_.origin==OriginKind::genesis&&(!anchor_.source_organism_id.empty()||!anchor_.source_checkpoint_digest.empty()))throw std::invalid_argument("genesis cannot import a prior continuity anchor");if(anchor_.origin==OriginKind::restore&&(anchor_.source_organism_id!=identity_.organism_id||!digest(anchor_.source_checkpoint_digest)))throw std::invalid_argument("restore must continue the same organism checkpoint");if((anchor_.origin==OriginKind::clone||anchor_.origin==OriginKind::fork)&&(anchor_.source_organism_id.empty()||anchor_.source_organism_id==identity_.organism_id||!digest(anchor_.source_checkpoint_digest)))throw std::invalid_argument("clone or fork requires a distinct source identity");if(anchor_.origin==OriginKind::child&&(!anchor_.source_organism_id.empty()||!anchor_.source_checkpoint_digest.empty()))throw std::invalid_argument("child autobiography begins at birth");}
bool AutobiographicalContinuity::append(std::string id,const memory::MemoryNode&m,std::uint64_t sequence,std::uint64_t at,std::string*e){if(e)e->clear();if(!events_.empty()&&events_.back().sequence==std::numeric_limits<std::uint64_t>::max()){fail(e,"life-event sequence exhausted");return false;}const auto expected=events_.empty()?1:events_.back().sequence+1;const auto previous=events_.empty()?anchor_.source_checkpoint_digest:events_.back().event_digest;if(events_.size()>=event_capacity_||!text(id)||!text(m.id)||!digest(m.content_digest)||!digest(m.provenance_digest)||sequence!=expected||(!events_.empty()&&at<events_.back().logical_time)||std::any_of(events_.begin(),events_.end(),[&](const auto&x){return x.id==id||x.memory_id==m.id;})){fail(e,"invalid duplicate gap or over-capacity life event");return false;}if(m.origin==memory::Origin::direct_experience&&(m.owner_id!=identity_.organism_id||m.scope!=memory::IdentityScope::organism_private)){fail(e,"foreign or shared memory cannot become direct experience");return false;}LifeEvent x{std::move(id),m.id,m.content_digest,m.provenance_digest,previous,{},m.origin,m.scope,sequence,at};x.event_digest=event_hash(identity_.organism_id,x);events_.push_back(std::move(x));return true;}
bool AutobiographicalContinuity::checkpoint(std::string id,std::uint64_t at,std::string*e){if(e)e->clear();if(checkpoints_.size()>=checkpoint_capacity_||events_.empty()||!text(id)||at<events_.back().logical_time||std::any_of(checkpoints_.begin(),checkpoints_.end(),[&](const auto&x){return x.id==id;})){fail(e,"invalid duplicate or over-capacity continuity checkpoint");return false;}ContinuityCheckpoint c{std::move(id),events_.back().event_digest,{},events_.back().sequence,at};c.checkpoint_digest=runtime::sha256("continuity-checkpoint-v1|"+identity_.organism_id+"|"+c.id+"|"+std::to_string(c.sequence)+"|"+std::to_string(c.logical_time)+"|"+c.head_event_digest);checkpoints_.push_back(std::move(c));return true;}
SegmentAudit AutobiographicalContinuity::inspect_segment(const std::vector<LifeEvent>& s)const{SegmentAudit a;std::uint64_t sequence=events_.empty()?1:events_.back().sequence+1;std::string previous=events_.empty()?anchor_.source_checkpoint_digest:events_.back().event_digest;std::vector<std::string> ids,memory_ids;for(const auto&x:s){if(x.sequence!=sequence)++a.gaps;if(std::find(ids.begin(),ids.end(),x.id)!=ids.end()||std::find(memory_ids.begin(),memory_ids.end(),x.memory_id)!=memory_ids.end()||std::any_of(events_.begin(),events_.end(),[&](const auto&e){return e.id==x.id||e.memory_id==x.memory_id;}))++a.conflicts;if(x.memory_origin==memory::Origin::direct_experience&&x.scope!=memory::IdentityScope::organism_private)++a.invalid_origins;if(!digest(x.content_digest)||!digest(x.provenance_digest)||x.previous_event_digest!=previous||x.event_digest!=event_hash(identity_.organism_id,x))++a.invalid_digests;ids.push_back(x.id);memory_ids.push_back(x.memory_id);sequence=x.sequence+1;previous=x.event_digest;}return a;}
bool AutobiographicalContinuity::verify()const{if(!validate(identity_).empty()||events_.size()>event_capacity_||checkpoints_.size()>checkpoint_capacity_)return false;std::uint64_t seq=1;std::string previous=anchor_.source_checkpoint_digest;std::uint64_t time=0;std::set<std::string> event_ids,memory_ids,checkpoint_ids;for(const auto&x:events_){if(!text(x.id)||!text(x.memory_id)||!event_ids.insert(x.id).second||!memory_ids.insert(x.memory_id).second||x.sequence!=seq++||x.logical_time<time||x.previous_event_digest!=previous||x.event_digest!=event_hash(identity_.organism_id,x)||!digest(x.content_digest)||!digest(x.provenance_digest)||(x.memory_origin==memory::Origin::direct_experience&&x.scope!=memory::IdentityScope::organism_private))return false;time=x.logical_time;previous=x.event_digest;}for(const auto&c:checkpoints_){if(!text(c.id)||!checkpoint_ids.insert(c.id).second||!digest(c.head_event_digest)||!digest(c.checkpoint_digest)||!c.sequence||c.sequence>events_.size())return false;const auto&event=events_[static_cast<std::size_t>(c.sequence-1)];if(c.head_event_digest!=event.event_digest||c.logical_time<event.logical_time||c.checkpoint_digest!=runtime::sha256("continuity-checkpoint-v1|"+identity_.organism_id+"|"+c.id+"|"+std::to_string(c.sequence)+"|"+std::to_string(c.logical_time)+"|"+c.head_event_digest))return false;}return true;}
}
