#include "genesis/cognition/persistence.hpp"
#include "genesis/runtime/runtime.hpp"
#include <bit>
#include <cctype>
#include <fstream>
#include <iterator>
#include <stdexcept>
namespace genesis::cognition {namespace {
constexpr std::string_view magic="GENESIS-BELIEF";constexpr std::uint64_t schema=1,max_items=1000000,max_field=16U*1024U*1024U;
void err(BeliefStoreError*e,BeliefStoreErrorCode c,std::string m){if(e){e->code=c;e->message=std::move(m);}}
void idok(std::string_view s){if(s.empty()||s.size()>128||s=="."||s=="..")throw std::invalid_argument("unsafe identifier");for(unsigned char c:s)if(!std::isalnum(c)&&c!='_'&&c!='-'&&c!='.')throw std::invalid_argument("unsafe identifier character");}
void u64(std::string&o,std::uint64_t v){for(unsigned s=0;s<64;s+=8)o.push_back(static_cast<char>((v>>s)&255));}std::uint64_t get64(std::string_view b,std::size_t&o){if(o>b.size()||b.size()-o<8)throw std::runtime_error("truncated integer");std::uint64_t v=0;for(unsigned s=0;s<64;s+=8)v|=static_cast<std::uint64_t>(static_cast<unsigned char>(b[o++]))<<s;return v;}void str(std::string&o,std::string_view s){u64(o,s.size());o.append(s);}std::string getstr(std::string_view b,std::size_t&o){const auto n=get64(b,o);if(n>max_field||n>b.size()-o)throw std::runtime_error("invalid field length");std::string s(b.substr(o,n));o+=n;return s;}std::string readall(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("cannot open belief record");std::string b{std::istreambuf_iterator<char>(f),{}};if(f.bad())throw std::runtime_error("cannot read belief record");return b;}
}
BeliefStore::BeliefStore(std::filesystem::path root,std::size_t maximum):root_(std::move(root)),maximum_record_bytes_(maximum){if(root_.empty()||maximum<1024)throw std::invalid_argument("invalid belief store configuration");}
std::string BeliefStore::serialize(const BeliefModel&m){if(!m.verify())throw std::invalid_argument("invalid belief model");std::string o(magic);u64(o,schema);str(o,m.owner_id());u64(o,m.capacity());u64(o,m.beliefs().size());for(const auto&b:m.beliefs()){str(o,b.id);str(o,b.proposition);str(o,b.evidence_digest);u64(o,static_cast<std::uint64_t>(b.model));u64(o,std::bit_cast<std::uint64_t>(b.confidence));u64(o,std::bit_cast<std::uint64_t>(b.uncertainty));u64(o,b.observed_at);str(o,b.claim_key);u64(o,b.affirmation);u64(o,static_cast<std::uint64_t>(b.state));str(o,b.supersedes_id);str(o,b.source_id);u64(o,std::bit_cast<std::uint64_t>(b.source_quality));}o+=runtime::sha256(o);return o;}
std::optional<BeliefModel> BeliefStore::deserialize(std::string_view bytes,BeliefStoreError*e){try{if(bytes.size()<magic.size()+8+64||bytes.substr(0,magic.size())!=magic)throw std::runtime_error("invalid belief magic");const auto payload=bytes.substr(0,bytes.size()-64);if(runtime::sha256(payload)!=bytes.substr(bytes.size()-64))throw std::runtime_error("belief checksum mismatch");std::size_t o=magic.size();if(get64(payload,o)!=schema){err(e,BeliefStoreErrorCode::unsupported_schema,"unsupported belief schema");return std::nullopt;}auto owner=getstr(payload,o);const auto capacity=get64(payload,o),count=get64(payload,o);if(!capacity||capacity>max_items||count>capacity)throw std::runtime_error("invalid belief capacity");BeliefModel model(owner,capacity);std::vector<BeliefState> desired;desired.reserve(count);while(desired.size()<count){Belief b;b.id=getstr(payload,o);b.proposition=getstr(payload,o);b.evidence_digest=getstr(payload,o);const auto kind=get64(payload,o);b.confidence=std::bit_cast<double>(get64(payload,o));b.uncertainty=std::bit_cast<double>(get64(payload,o));b.observed_at=get64(payload,o);b.claim_key=getstr(payload,o);b.affirmation=get64(payload,o)!=0;const auto state=get64(payload,o);b.supersedes_id=getstr(payload,o);b.source_id=getstr(payload,o);b.source_quality=std::bit_cast<double>(get64(payload,o));if(kind>static_cast<std::uint64_t>(ModelKind::other_agent)||state>static_cast<std::uint64_t>(BeliefState::retracted))throw std::runtime_error("invalid belief enum");b.model=static_cast<ModelKind>(kind);const auto target=static_cast<BeliefState>(state);b.state=BeliefState::active;const auto id=b.id;const auto evidence=b.evidence_digest;const auto time=b.observed_at;if(!model.update(std::move(b)))throw std::runtime_error("invalid belief record");if(target==BeliefState::retracted&&!model.retract(id,evidence,time))throw std::runtime_error("invalid belief retraction");desired.push_back(target);}if(o!=payload.size()||!model.verify()||model.beliefs().size()!=desired.size())throw std::runtime_error("trailing or invalid belief data");for(std::size_t i=0;i<desired.size();++i)if(model.beliefs()[i].state!=desired[i])throw std::runtime_error("belief state reconstruction mismatch");err(e,BeliefStoreErrorCode::none,{});return model;}catch(const std::exception&x){err(e,BeliefStoreErrorCode::corrupt_record,x.what());return std::nullopt;}}
bool BeliefStore::write(const BeliefModel&m,std::string_view version,BeliefStoreError*e)const{try{idok(m.owner_id());idok(version);auto bytes=serialize(m);if(bytes.size()>maximum_record_bytes_)throw std::invalid_argument("belief record exceeds configured limit");std::error_code ec;std::filesystem::create_directories(root_,ec);if(ec)throw std::runtime_error("cannot create belief store");const auto target=root_/(m.owner_id()+"."+std::string(version)+".belief");if(std::filesystem::exists(target)){if(readall(target)==bytes){err(e,BeliefStoreErrorCode::none,{});return true;}err(e,BeliefStoreErrorCode::conflicting_version,"immutable belief version conflict");return false;}const auto temp=std::filesystem::path(target.string()+".tmp-"+runtime::sha256(bytes));{std::ofstream f(temp,std::ios::binary|std::ios::trunc);f.write(bytes.data(),static_cast<std::streamsize>(bytes.size()));f.flush();if(!f)throw std::runtime_error("cannot flush belief record");}std::filesystem::rename(temp,target,ec);if(ec){std::filesystem::remove(temp);throw std::runtime_error("cannot atomically commit belief record");}err(e,BeliefStoreErrorCode::none,{});return true;}catch(const std::invalid_argument&x){err(e,BeliefStoreErrorCode::invalid_model,x.what());return false;}catch(const std::exception&x){err(e,BeliefStoreErrorCode::io_error,x.what());return false;}}
std::optional<BeliefModel> BeliefStore::read(std::string_view owner,std::string_view version,BeliefStoreError*e)const{try{idok(owner);idok(version);const auto path=root_/(std::string(owner)+"."+std::string(version)+".belief");if(!std::filesystem::exists(path)){err(e,BeliefStoreErrorCode::not_found,"belief record not found");return std::nullopt;}const auto bytes=readall(path);if(bytes.size()>maximum_record_bytes_){err(e,BeliefStoreErrorCode::corrupt_record,"belief record exceeds configured limit");return std::nullopt;}auto model=deserialize(bytes,e);if(model&&model->owner_id()!=owner){err(e,BeliefStoreErrorCode::corrupt_record,"belief owner mismatch");return std::nullopt;}return model;}catch(const std::invalid_argument&x){err(e,BeliefStoreErrorCode::invalid_identifier,x.what());return std::nullopt;}catch(const std::exception&x){err(e,BeliefStoreErrorCode::io_error,x.what());return std::nullopt;}}
}
