#include "genesis/cognition/workspace.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <set>
#include <stdexcept>
namespace genesis::cognition { namespace { bool ok(std::string_view s){return !s.empty()&&s.size()<=1024;} bool ratio(double v){return std::isfinite(v)&&v>=0&&v<=1;}bool digest(std::string_view s){return s.size()==64&&std::all_of(s.begin(),s.end(),[](unsigned char c){return std::isxdigit(c)!=0;});} }
BeliefModel::BeliefModel(std::string id,std::size_t c):owner_id_(std::move(id)),capacity_(c){if(!ok(owner_id_)||!c)throw std::invalid_argument("invalid belief model");}
bool BeliefModel::update(Belief b){if(!ok(b.id)||!ok(b.proposition)||!digest(b.evidence_digest)||!ratio(b.confidence)||!ratio(b.uncertainty)||(!b.claim_key.empty()&&!ok(b.claim_key))||!ok(b.source_id)||!ratio(b.source_quality)||b.state!=BeliefState::active||static_cast<unsigned>(b.model)>static_cast<unsigned>(ModelKind::other_agent)||b.supersedes_id==b.id||std::any_of(beliefs_.begin(),beliefs_.end(),[&](const auto&x){return x.id==b.id;}))return false;if(beliefs_.size()>=capacity_)return false;if(!b.supersedes_id.empty()){auto prior=std::find_if(beliefs_.begin(),beliefs_.end(),[&](const auto&x){return x.id==b.supersedes_id;});if(prior==beliefs_.end()||prior->state!=BeliefState::active||b.observed_at<prior->observed_at)return false;prior->state=BeliefState::superseded;}beliefs_.push_back(std::move(b));return true;}
bool BeliefModel::retract(std::string_view id,std::string_view evidence,std::uint64_t observed){auto it=std::find_if(beliefs_.begin(),beliefs_.end(),[&](const auto&x){return x.id==id;});if(it==beliefs_.end()||it->state!=BeliefState::active||!digest(evidence)||observed<it->observed_at)return false;it->state=BeliefState::retracted;it->evidence_digest=std::string(evidence);it->observed_at=observed;return true;}
const Belief* BeliefModel::find(std::string_view id)const noexcept{auto it=std::find_if(beliefs_.begin(),beliefs_.end(),[&](const auto&b){return b.id==id;});return it==beliefs_.end()?nullptr:&*it;}
std::vector<Belief> BeliefModel::contradictions(std::string_view key)const{std::vector<Belief> candidates;bool positive=false,negative=false;for(const auto&b:beliefs_)if(b.state==BeliefState::active&&b.claim_key==key&&b.confidence>.5){candidates.push_back(b);positive|=b.affirmation;negative|=!b.affirmation;}return positive&&negative?candidates:std::vector<Belief>{};}
std::optional<double> BeliefModel::assessed_confidence(std::string_view id,std::uint64_t now,std::uint64_t window)const{const auto*b=find(id);if(!b||!window||now<b->observed_at||b->state!=BeliefState::active)return std::nullopt;const auto age=now-b->observed_at;const double freshness=age>=window?0.0:1.0-static_cast<double>(age)/static_cast<double>(window);return b->confidence*b->source_quality*freshness;}
bool BeliefModel::verify()const{if(!ok(owner_id_)||!capacity_||beliefs_.size()>capacity_)return false;std::set<std::string>ids;for(const auto&b:beliefs_)if(!ids.insert(b.id).second||!ok(b.id)||!ok(b.proposition)||!digest(b.evidence_digest)||!ratio(b.confidence)||!ratio(b.uncertainty)||(!b.claim_key.empty()&&!ok(b.claim_key))||!ok(b.source_id)||!ratio(b.source_quality)||static_cast<unsigned>(b.model)>static_cast<unsigned>(ModelKind::other_agent)||static_cast<unsigned>(b.state)>static_cast<unsigned>(BeliefState::retracted)||b.supersedes_id==b.id)return false;for(const auto&b:beliefs_)if(b.state==BeliefState::superseded&&!std::any_of(beliefs_.begin(),beliefs_.end(),[&](const auto&x){return x.supersedes_id==b.id;}))return false;return true;}
const std::string& BeliefModel::owner_id()const noexcept{return owner_id_;}std::size_t BeliefModel::capacity()const noexcept{return capacity_;}const std::vector<Belief>& BeliefModel::beliefs()const noexcept{return beliefs_;}
ConsciousWorkspace::ConsciousWorkspace(std::size_t c):capacity_(c){if(!c)throw std::invalid_argument("workspace capacity must be positive");}
bool ConsciousWorkspace::submit(WorkspaceItem i){if(!ok(i.id)||!ok(i.source)||i.payload_digest.size()!=64||!ratio(i.salience)||!ratio(i.confidence)||std::any_of(items_.begin(),items_.end(),[&](const auto&x){return x.id==i.id;}))return false;items_.push_back(std::move(i));std::sort(items_.begin(),items_.end(),[](const auto&a,const auto&b){const double as=a.inhibited?-1:a.salience*a.confidence,bs=b.inhibited?-1:b.salience*b.confidence;return as!=bs?as>bs:a.timestamp<b.timestamp;});if(items_.size()>capacity_)items_.resize(capacity_);return true;}
std::vector<WorkspaceItem> ConsciousWorkspace::focus()const{std::vector<WorkspaceItem> out;for(const auto&i:items_)if(!i.inhibited)out.push_back(i);return out;}
IntrospectionReport ConsciousWorkspace::introspect()const{IntrospectionReport r;r.candidates=items_.size();for(const auto&i:items_){if(i.inhibited)++r.inhibited;else{++r.admitted;r.mean_confidence+=i.confidence;}}if(r.admitted)r.mean_confidence/=r.admitted;r.uncertainty=1-r.mean_confidence;return r;}
void ConsciousWorkspace::clear()noexcept{items_.clear();}
}
