#include "genesis/cognition/world_model.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <set>
#include <stdexcept>
#include <limits>
#include <deque>
namespace genesis::cognition {namespace {bool text(std::string_view s){return !s.empty()&&s.size()<=1024&&std::all_of(s.begin(),s.end(),[](unsigned char c){return c>=0x20&&c!=0x7f;});}bool digest(std::string_view s){return s.size()==64&&std::all_of(s.begin(),s.end(),[](unsigned char c){return std::isxdigit(c)!=0;});}bool ratio(double v){return std::isfinite(v)&&v>=0&&v<=1;}void failure(std::string*e,const char*m){if(e)*e=m;}}
WorldDynamics::WorldDynamics(std::string owner,std::size_t sc,std::size_t hc,std::size_t pc):organism_id_(std::move(owner)),state_capacity_(sc),hypothesis_capacity_(hc),prediction_capacity_(pc){if(!text(organism_id_)||!sc||!hc||!pc)throw std::invalid_argument("invalid world dynamics configuration");states_.reserve(sc);}
bool WorldDynamics::observe_state(WorldStateObservation x,std::string*e){if(e)e->clear();if(states_.size()>=state_capacity_||!text(x.id)||!text(x.entity_id)||!text(x.property)||!digest(x.value_digest)||!digest(x.evidence_digest)||!ratio(x.confidence)||std::any_of(states_.begin(),states_.end(),[&](const auto&v){return v.id==x.id;})){failure(e,"invalid duplicate or over-capacity world observation");return false;}states_.push_back(std::move(x));return true;}
bool WorldDynamics::register_hypothesis(CausalHypothesis h,std::string*e){if(e)e->clear();if(hypotheses_.size()>=hypothesis_capacity_||!text(h.id)||hypotheses_.contains(h.id)||!text(h.cause_property)||!digest(h.cause_value_digest)||!text(h.effect_property)||!digest(h.effect_value_digest)||!digest(h.evidence_digest)||!ratio(h.prior_confidence)||!ratio(h.calibrated_confidence)||h.updated_at<h.created_at){failure(e,"invalid duplicate or over-capacity causal hypothesis");return false;}hypotheses_.emplace(h.id,std::move(h));return true;}
bool WorldDynamics::issue_prediction(WorldPrediction p,std::string*e){if(e)e->clear();const auto h=hypotheses_.find(p.hypothesis_id);if(predictions_.size()>=prediction_capacity_||!text(p.id)||predictions_.contains(p.id)||h==hypotheses_.end()||!text(p.entity_id)||!digest(p.expected_value_digest)||p.expected_value_digest!=h->second.effect_value_digest||p.due_at<=p.issued_at||!ratio(p.issued_confidence)||p.state!=PredictionState::pending||!p.outcome_evidence_digest.empty()||p.resolved_at){failure(e,"invalid duplicate or over-capacity world prediction");return false;}predictions_.emplace(p.id,std::move(p));return true;}
bool WorldDynamics::resolve_prediction(std::string_view id,std::string_view observed,std::string_view evidence,std::uint64_t at,std::string*e){if(e)e->clear();auto p=predictions_.find(std::string(id));if(p==predictions_.end()||p->second.state!=PredictionState::pending||!digest(observed)||!digest(evidence)||at<p->second.issued_at){failure(e,"invalid or unavailable prediction outcome");return false;}auto h=hypotheses_.find(p->second.hypothesis_id);if(h==hypotheses_.end()||h->second.support_count==std::numeric_limits<std::uint64_t>::max()||h->second.counterevidence_count==std::numeric_limits<std::uint64_t>::max()){failure(e,"prediction hypothesis missing or counter exhausted");return false;}const bool confirmed=observed==p->second.expected_value_digest;p->second.state=confirmed?PredictionState::confirmed:PredictionState::refuted;p->second.outcome_evidence_digest=std::string(evidence);p->second.resolved_at=at;h->second.updated_at=std::max(h->second.updated_at,at);if(confirmed)++h->second.support_count;else ++h->second.counterevidence_count;const double total=static_cast<double>(h->second.support_count)+static_cast<double>(h->second.counterevidence_count);const double observed_rate=static_cast<double>(h->second.support_count)/total;h->second.calibrated_confidence=std::clamp(h->second.prior_confidence*.25+observed_rate*.75,0.0,1.0);return true;}
std::size_t WorldDynamics::expire_predictions(std::uint64_t now){std::size_t n=0;for(auto&[_,p]:predictions_)if(p.state==PredictionState::pending&&now>p.due_at){p.state=PredictionState::expired;p.resolved_at=now;++n;}return n;}
std::vector<CounterfactualResult> WorldDynamics::simulate(std::string_view property,std::string_view value,std::size_t maximum)const{std::vector<CounterfactualResult> out;if(!maximum||!text(property)||!digest(value))return out;for(const auto&[_,h]:hypotheses_)if(h.cause_property==property&&h.cause_value_digest==value)out.push_back({h.id,h.effect_property,h.effect_value_digest,h.calibrated_confidence,true});std::sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.confidence!=b.confidence?a.confidence>b.confidence:a.hypothesis_id<b.hypothesis_id;});if(out.size()>maximum)out.resize(maximum);return out;}
CounterfactualSearchResult WorldDynamics::simulate_intervention(const Intervention& intervention,const SimulationLimits& limits)const{
 CounterfactualSearchResult result;
 if(!text(intervention.property)||!digest(intervention.value_digest)||!limits.maximum_depth||!limits.maximum_branches_per_node||!limits.maximum_paths||!limits.maximum_expansions||!ratio(limits.minimum_confidence))return result;
 const auto rank_paths=[&]{std::stable_sort(result.paths.begin(),result.paths.end(),[](const auto&a,const auto&b){if(a.accumulated_confidence!=b.accumulated_confidence)return a.accumulated_confidence>b.accumulated_confidence;if(a.steps.size()!=b.steps.size())return a.steps.size()<b.steps.size();return a.steps.back().hypothesis_id<b.steps.back().hypothesis_id;});};
 struct Node{std::string property,value;std::vector<CounterfactualStep> steps;std::set<std::pair<std::string,std::string>> visited;double confidence{1};bool unresolved_confounders{false};};
 std::deque<Node> pending;Node root{intervention.property,intervention.value_digest,{},{},1,false};root.visited.emplace(root.property,root.value);pending.push_back(std::move(root));
 while(!pending.empty()&&result.paths.size()<limits.maximum_paths){
  Node node=std::move(pending.front());pending.pop_front();
  std::vector<const CausalHypothesis*> matches;for(const auto&[_,h]:hypotheses_)if(h.cause_property==node.property&&h.cause_value_digest==node.value)matches.push_back(&h);
  std::sort(matches.begin(),matches.end(),[](const auto*a,const auto*b){return a->calibrated_confidence!=b->calibrated_confidence?a->calibrated_confidence>b->calibrated_confidence:a->id<b->id;});
  if(node.steps.size()>=limits.maximum_depth){if(!matches.empty())result.depth_limited=true;continue;}
  const bool confounded=matches.size()>1;
  if(matches.size()>limits.maximum_branches_per_node){matches.resize(limits.maximum_branches_per_node);result.branch_limited=true;}
  for(const auto*h:matches){
   if(result.expanded_nodes>=limits.maximum_expansions){result.budget_exhausted=true;rank_paths();return result;}
   ++result.expanded_nodes;const double confidence=node.confidence*h->calibrated_confidence;if(confidence<limits.minimum_confidence)continue;
   const auto key=std::pair{h->effect_property,h->effect_value_digest};if(node.visited.contains(key))continue;
   Node child{h->effect_property,h->effect_value_digest,node.steps,node.visited,confidence,node.unresolved_confounders||confounded};child.steps.push_back({h->id,h->cause_property,h->cause_value_digest,h->effect_property,h->effect_value_digest,h->calibrated_confidence});child.visited.insert(key);
   result.paths.push_back({child.steps,child.property,child.value,confidence,true,false,child.unresolved_confounders});if(result.paths.size()>=limits.maximum_paths){result.path_limited=true;rank_paths();return result;}
   pending.push_back(std::move(child));
  }
 }
 rank_paths();
 return result;
}
const WorldPrediction* WorldDynamics::find_prediction(std::string_view id)const noexcept{const auto it=predictions_.find(std::string(id));return it==predictions_.end()?nullptr:&it->second;}const CausalHypothesis* WorldDynamics::find_hypothesis(std::string_view id)const noexcept{const auto it=hypotheses_.find(std::string(id));return it==hypotheses_.end()?nullptr:&it->second;}
bool WorldDynamics::verify()const{if(!text(organism_id_)||states_.size()>state_capacity_||hypotheses_.size()>hypothesis_capacity_||predictions_.size()>prediction_capacity_)return false;std::set<std::string> ids;for(const auto&x:states_)if(!ids.insert(x.id).second||!text(x.entity_id)||!text(x.property)||!digest(x.value_digest)||!digest(x.evidence_digest)||!ratio(x.confidence))return false;for(const auto&[id,h]:hypotheses_){if(id!=h.id||!text(h.cause_property)||!digest(h.cause_value_digest)||!text(h.effect_property)||!digest(h.effect_value_digest)||!digest(h.evidence_digest)||!ratio(h.prior_confidence)||!ratio(h.calibrated_confidence)||h.updated_at<h.created_at)return false;const double total=static_cast<double>(h.support_count)+static_cast<double>(h.counterevidence_count);const double expected=total?h.prior_confidence*.25+(static_cast<double>(h.support_count)/total)*.75:h.prior_confidence;if(std::abs(h.calibrated_confidence-expected)>1e-12)return false;}for(const auto&[id,p]:predictions_){const auto h=hypotheses_.find(p.hypothesis_id);if(id!=p.id||!text(p.entity_id)||h==hypotheses_.end()||!digest(p.expected_value_digest)||p.expected_value_digest!=h->second.effect_value_digest||!ratio(p.issued_confidence)||p.due_at<=p.issued_at||static_cast<unsigned>(p.state)>static_cast<unsigned>(PredictionState::expired)||(p.state==PredictionState::pending&&p.resolved_at)||(p.state!=PredictionState::pending&&!p.resolved_at))return false;if((p.state==PredictionState::confirmed||p.state==PredictionState::refuted)&&!digest(p.outcome_evidence_digest))return false;if((p.state==PredictionState::pending||p.state==PredictionState::expired)&&!p.outcome_evidence_digest.empty())return false;}return true;}
const std::string& WorldDynamics::organism_id()const noexcept{return organism_id_;}std::size_t WorldDynamics::state_count()const noexcept{return states_.size();}std::size_t WorldDynamics::hypothesis_count()const noexcept{return hypotheses_.size();}std::size_t WorldDynamics::prediction_count()const noexcept{return predictions_.size();}std::size_t WorldDynamics::state_capacity()const noexcept{return state_capacity_;}std::size_t WorldDynamics::hypothesis_capacity()const noexcept{return hypothesis_capacity_;}std::size_t WorldDynamics::prediction_capacity()const noexcept{return prediction_capacity_;}const std::vector<WorldStateObservation>& WorldDynamics::states()const noexcept{return states_;}const std::map<std::string,CausalHypothesis>& WorldDynamics::hypotheses()const noexcept{return hypotheses_;}const std::map<std::string,WorldPrediction>& WorldDynamics::predictions()const noexcept{return predictions_;}
}
