#include "genesis/cognition/world_model.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <set>
#include <stdexcept>
#include <limits>
namespace genesis::cognition {namespace {bool text(std::string_view s){return !s.empty()&&s.size()<=1024&&std::all_of(s.begin(),s.end(),[](unsigned char c){return c>=0x20&&c!=0x7f;});}bool digest(std::string_view s){return s.size()==64&&std::all_of(s.begin(),s.end(),[](unsigned char c){return std::isxdigit(c)!=0;});}bool ratio(double v){return std::isfinite(v)&&v>=0&&v<=1;}void failure(std::string*e,const char*m){if(e)*e=m;}}
WorldDynamics::WorldDynamics(std::string owner,std::size_t sc,std::size_t hc,std::size_t pc):organism_id_(std::move(owner)),state_capacity_(sc),hypothesis_capacity_(hc),prediction_capacity_(pc){if(!text(organism_id_)||!sc||!hc||!pc)throw std::invalid_argument("invalid world dynamics configuration");states_.reserve(sc);}
bool WorldDynamics::observe_state(WorldStateObservation x,std::string*e){if(e)e->clear();if(states_.size()>=state_capacity_||!text(x.id)||!text(x.entity_id)||!text(x.property)||!digest(x.value_digest)||!digest(x.evidence_digest)||!ratio(x.confidence)||std::any_of(states_.begin(),states_.end(),[&](const auto&v){return v.id==x.id;})){failure(e,"invalid duplicate or over-capacity world observation");return false;}states_.push_back(std::move(x));return true;}
bool WorldDynamics::register_hypothesis(CausalHypothesis h,std::string*e){if(e)e->clear();if(hypotheses_.size()>=hypothesis_capacity_||!text(h.id)||hypotheses_.contains(h.id)||!text(h.cause_property)||!digest(h.cause_value_digest)||!text(h.effect_property)||!digest(h.effect_value_digest)||!digest(h.evidence_digest)||!ratio(h.prior_confidence)||!ratio(h.calibrated_confidence)||h.updated_at<h.created_at){failure(e,"invalid duplicate or over-capacity causal hypothesis");return false;}hypotheses_.emplace(h.id,std::move(h));return true;}
bool WorldDynamics::issue_prediction(WorldPrediction p,std::string*e){if(e)e->clear();const auto h=hypotheses_.find(p.hypothesis_id);if(predictions_.size()>=prediction_capacity_||!text(p.id)||predictions_.contains(p.id)||h==hypotheses_.end()||!text(p.entity_id)||!digest(p.expected_value_digest)||p.expected_value_digest!=h->second.effect_value_digest||p.due_at<=p.issued_at||!ratio(p.issued_confidence)||p.state!=PredictionState::pending||!p.outcome_evidence_digest.empty()||p.resolved_at){failure(e,"invalid duplicate or over-capacity world prediction");return false;}predictions_.emplace(p.id,std::move(p));return true;}
bool WorldDynamics::resolve_prediction(std::string_view id,std::string_view observed,std::string_view evidence,std::uint64_t at,std::string*e){if(e)e->clear();auto p=predictions_.find(std::string(id));if(p==predictions_.end()||p->second.state!=PredictionState::pending||!digest(observed)||!digest(evidence)||at<p->second.issued_at){failure(e,"invalid or unavailable prediction outcome");return false;}auto h=hypotheses_.find(p->second.hypothesis_id);if(h==hypotheses_.end()||h->second.support_count==std::numeric_limits<std::uint64_t>::max()||h->second.counterevidence_count==std::numeric_limits<std::uint64_t>::max()){failure(e,"prediction hypothesis missing or counter exhausted");return false;}const bool confirmed=observed==p->second.expected_value_digest;p->second.state=confirmed?PredictionState::confirmed:PredictionState::refuted;p->second.outcome_evidence_digest=std::string(evidence);p->second.resolved_at=at;h->second.updated_at=std::max(h->second.updated_at,at);if(confirmed)++h->second.support_count;else ++h->second.counterevidence_count;const double total=static_cast<double>(h->second.support_count)+static_cast<double>(h->second.counterevidence_count);const double observed_rate=static_cast<double>(h->second.support_count)/total;h->second.calibrated_confidence=std::clamp(h->second.prior_confidence*.25+observed_rate*.75,0.0,1.0);return true;}
std::size_t WorldDynamics::expire_predictions(std::uint64_t now){std::size_t n=0;for(auto&[_,p]:predictions_)if(p.state==PredictionState::pending&&now>p.due_at){p.state=PredictionState::expired;p.resolved_at=now;++n;}return n;}
std::vector<CounterfactualResult> WorldDynamics::simulate(std::string_view property,std::string_view value,std::size_t maximum)const{std::vector<CounterfactualResult> out;if(!maximum||!text(property)||!digest(value))return out;for(const auto&[_,h]:hypotheses_)if(h.cause_property==property&&h.cause_value_digest==value)out.push_back({h.id,h.effect_property,h.effect_value_digest,h.calibrated_confidence,true});std::sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.confidence!=b.confidence?a.confidence>b.confidence:a.hypothesis_id<b.hypothesis_id;});if(out.size()>maximum)out.resize(maximum);return out;}
const WorldPrediction* WorldDynamics::find_prediction(std::string_view id)const noexcept{const auto it=predictions_.find(std::string(id));return it==predictions_.end()?nullptr:&it->second;}const CausalHypothesis* WorldDynamics::find_hypothesis(std::string_view id)const noexcept{const auto it=hypotheses_.find(std::string(id));return it==hypotheses_.end()?nullptr:&it->second;}
bool WorldDynamics::verify()const{if(!text(organism_id_)||states_.size()>state_capacity_||hypotheses_.size()>hypothesis_capacity_||predictions_.size()>prediction_capacity_)return false;std::set<std::string> ids;for(const auto&x:states_)if(!ids.insert(x.id).second||!text(x.entity_id)||!text(x.property)||!digest(x.value_digest)||!digest(x.evidence_digest)||!ratio(x.confidence))return false;for(const auto&[id,h]:hypotheses_)if(id!=h.id||!text(h.cause_property)||!digest(h.cause_value_digest)||!text(h.effect_property)||!digest(h.effect_value_digest)||!digest(h.evidence_digest)||!ratio(h.prior_confidence)||!ratio(h.calibrated_confidence)||h.updated_at<h.created_at)return false;for(const auto&[id,p]:predictions_){if(id!=p.id||!text(p.entity_id)||!hypotheses_.contains(p.hypothesis_id)||!digest(p.expected_value_digest)||!ratio(p.issued_confidence)||p.due_at<=p.issued_at||static_cast<unsigned>(p.state)>static_cast<unsigned>(PredictionState::expired)||(p.state==PredictionState::pending&&p.resolved_at)||(p.state!=PredictionState::pending&&!p.resolved_at))return false;if((p.state==PredictionState::confirmed||p.state==PredictionState::refuted)&&!digest(p.outcome_evidence_digest))return false;if((p.state==PredictionState::pending||p.state==PredictionState::expired)&&!p.outcome_evidence_digest.empty())return false;}return true;}
const std::string& WorldDynamics::organism_id()const noexcept{return organism_id_;}std::size_t WorldDynamics::state_count()const noexcept{return states_.size();}std::size_t WorldDynamics::hypothesis_count()const noexcept{return hypotheses_.size();}std::size_t WorldDynamics::prediction_count()const noexcept{return predictions_.size();}
}
