#include "genesis/cognition/world_persistence.hpp"
#include "genesis/runtime/runtime.hpp"
#include <bit>
#include <cctype>
#include <fstream>
#include <iterator>
#include <stdexcept>
namespace genesis::cognition {namespace {
constexpr std::string_view magic="GENESIS-WORLD-DYNAMICS";constexpr std::uint64_t schema=1,max_items=1000000,max_field=16U*1024U*1024U;
void err(WorldStoreError*e,WorldStoreErrorCode c,std::string m){if(e){e->code=c;e->message=std::move(m);}}void idok(std::string_view s){if(s.empty()||s.size()>128||s=="."||s=="..")throw std::invalid_argument("unsafe identifier");for(unsigned char c:s)if(!std::isalnum(c)&&c!='_'&&c!='-'&&c!='.')throw std::invalid_argument("unsafe identifier character");}void u64(std::string&o,std::uint64_t v){for(unsigned s=0;s<64;s+=8)o.push_back(static_cast<char>((v>>s)&255));}std::uint64_t get64(std::string_view b,std::size_t&o){if(o>b.size()||b.size()-o<8)throw std::runtime_error("truncated integer");std::uint64_t v=0;for(unsigned s=0;s<64;s+=8)v|=static_cast<std::uint64_t>(static_cast<unsigned char>(b[o++]))<<s;return v;}void str(std::string&o,std::string_view s){u64(o,s.size());o.append(s);}std::string getstr(std::string_view b,std::size_t&o){const auto n=get64(b,o);if(n>max_field||n>b.size()-o)throw std::runtime_error("invalid field length");std::string s(b.substr(o,n));o+=n;return s;}std::string readall(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("cannot open world record");std::string b{std::istreambuf_iterator<char>(f),{}};if(f.bad())throw std::runtime_error("cannot read world record");return b;}
}
WorldDynamicsStore::WorldDynamicsStore(std::filesystem::path root,std::size_t maximum):root_(std::move(root)),maximum_record_bytes_(maximum){if(root_.empty()||maximum<1024)throw std::invalid_argument("invalid world store configuration");}
std::string WorldDynamicsStore::serialize(const WorldDynamics&w){if(!w.verify())throw std::invalid_argument("invalid world dynamics");std::string o(magic);u64(o,schema);str(o,w.organism_id());u64(o,w.state_capacity());u64(o,w.hypothesis_capacity());u64(o,w.prediction_capacity());u64(o,w.states().size());for(const auto&x:w.states()){str(o,x.id);str(o,x.entity_id);str(o,x.property);str(o,x.value_digest);str(o,x.evidence_digest);u64(o,x.observed_at);u64(o,std::bit_cast<std::uint64_t>(x.confidence));}u64(o,w.hypotheses().size());for(const auto&[_,h]:w.hypotheses()){str(o,h.id);str(o,h.cause_property);str(o,h.cause_value_digest);str(o,h.effect_property);str(o,h.effect_value_digest);str(o,h.evidence_digest);u64(o,h.created_at);u64(o,h.updated_at);u64(o,h.support_count);u64(o,h.counterevidence_count);u64(o,std::bit_cast<std::uint64_t>(h.prior_confidence));u64(o,std::bit_cast<std::uint64_t>(h.calibrated_confidence));}u64(o,w.predictions().size());for(const auto&[_,p]:w.predictions()){str(o,p.id);str(o,p.hypothesis_id);str(o,p.entity_id);str(o,p.expected_value_digest);str(o,p.outcome_evidence_digest);u64(o,p.issued_at);u64(o,p.due_at);u64(o,p.resolved_at);u64(o,std::bit_cast<std::uint64_t>(p.issued_confidence));u64(o,static_cast<std::uint64_t>(p.state));}o+=runtime::sha256(o);return o;}
std::optional<WorldDynamics> WorldDynamicsStore::deserialize(std::string_view b,WorldStoreError*e){try{if(b.size()<magic.size()+8+64||b.substr(0,magic.size())!=magic)throw std::runtime_error("invalid world magic");const auto payload=b.substr(0,b.size()-64);if(runtime::sha256(payload)!=b.substr(b.size()-64))throw std::runtime_error("world checksum mismatch");std::size_t o=magic.size();if(get64(payload,o)!=schema){err(e,WorldStoreErrorCode::unsupported_schema,"unsupported world schema");return std::nullopt;}auto owner=getstr(payload,o);const auto sc=get64(payload,o),hc=get64(payload,o),pc=get64(payload,o);if(!sc||!hc||!pc||sc>max_items||hc>max_items||pc>max_items)throw std::runtime_error("invalid world capacities");WorldDynamics w(owner,sc,hc,pc);auto states=get64(payload,o);if(states>sc)throw std::runtime_error("state count exceeds capacity");while(states--){WorldStateObservation x;x.id=getstr(payload,o);x.entity_id=getstr(payload,o);x.property=getstr(payload,o);x.value_digest=getstr(payload,o);x.evidence_digest=getstr(payload,o);x.observed_at=get64(payload,o);x.confidence=std::bit_cast<double>(get64(payload,o));if(!w.observe_state(std::move(x)))throw std::runtime_error("invalid world observation");}auto hypotheses=get64(payload,o);if(hypotheses>hc)throw std::runtime_error("hypothesis count exceeds capacity");while(hypotheses--){CausalHypothesis h;h.id=getstr(payload,o);h.cause_property=getstr(payload,o);h.cause_value_digest=getstr(payload,o);h.effect_property=getstr(payload,o);h.effect_value_digest=getstr(payload,o);h.evidence_digest=getstr(payload,o);h.created_at=get64(payload,o);h.updated_at=get64(payload,o);h.support_count=get64(payload,o);h.counterevidence_count=get64(payload,o);h.prior_confidence=std::bit_cast<double>(get64(payload,o));h.calibrated_confidence=std::bit_cast<double>(get64(payload,o));if(!w.register_hypothesis(std::move(h)))throw std::runtime_error("invalid causal hypothesis");}auto predictions=get64(payload,o);if(predictions>pc)throw std::runtime_error("prediction count exceeds capacity");while(predictions--){WorldPrediction p;p.id=getstr(payload,o);p.hypothesis_id=getstr(payload,o);p.entity_id=getstr(payload,o);p.expected_value_digest=getstr(payload,o);p.outcome_evidence_digest=getstr(payload,o);p.issued_at=get64(payload,o);p.due_at=get64(payload,o);p.resolved_at=get64(payload,o);p.issued_confidence=std::bit_cast<double>(get64(payload,o));const auto state=get64(payload,o);if(state>static_cast<std::uint64_t>(PredictionState::expired)||w.predictions_.contains(p.id))throw std::runtime_error("invalid world prediction");p.state=static_cast<PredictionState>(state);w.predictions_.emplace(p.id,std::move(p));}if(o!=payload.size()||!w.verify())throw std::runtime_error("trailing or invalid world data");err(e,WorldStoreErrorCode::none,{});return w;}catch(const std::exception&x){err(e,WorldStoreErrorCode::corrupt_record,x.what());return std::nullopt;}}
bool WorldDynamicsStore::write(const WorldDynamics&w,std::string_view version,WorldStoreError*e)const{try{idok(w.organism_id());idok(version);auto bytes=serialize(w);if(bytes.size()>maximum_record_bytes_)throw std::invalid_argument("world record exceeds configured limit");std::error_code ec;std::filesystem::create_directories(root_,ec);if(ec)throw std::runtime_error("cannot create world store");const auto target=root_/(w.organism_id()+"."+std::string(version)+".world");if(std::filesystem::exists(target)){if(readall(target)==bytes){err(e,WorldStoreErrorCode::none,{});return true;}err(e,WorldStoreErrorCode::conflicting_version,"immutable world version conflict");return false;}const auto temp=std::filesystem::path(target.string()+".tmp-"+runtime::sha256(bytes));{std::ofstream f(temp,std::ios::binary|std::ios::trunc);f.write(bytes.data(),static_cast<std::streamsize>(bytes.size()));f.flush();if(!f)throw std::runtime_error("cannot flush world record");}std::filesystem::rename(temp,target,ec);if(ec){std::filesystem::remove(temp);throw std::runtime_error("cannot atomically commit world record");}err(e,WorldStoreErrorCode::none,{});return true;}catch(const std::invalid_argument&x){err(e,WorldStoreErrorCode::invalid_model,x.what());return false;}catch(const std::exception&x){err(e,WorldStoreErrorCode::io_error,x.what());return false;}}
std::optional<WorldDynamics> WorldDynamicsStore::read(std::string_view owner,std::string_view version,WorldStoreError*e)const{try{idok(owner);idok(version);const auto path=root_/(std::string(owner)+"."+std::string(version)+".world");if(!std::filesystem::exists(path)){err(e,WorldStoreErrorCode::not_found,"world record not found");return std::nullopt;}const auto bytes=readall(path);if(bytes.size()>maximum_record_bytes_){err(e,WorldStoreErrorCode::corrupt_record,"world record exceeds configured limit");return std::nullopt;}auto world=deserialize(bytes,e);if(world&&world->organism_id()!=owner){err(e,WorldStoreErrorCode::corrupt_record,"world owner mismatch");return std::nullopt;}return world;}catch(const std::invalid_argument&x){err(e,WorldStoreErrorCode::invalid_identifier,x.what());return std::nullopt;}catch(const std::exception&x){err(e,WorldStoreErrorCode::io_error,x.what());return std::nullopt;}}
}
