#include "genesis/learning/consolidation.hpp"
#include <cstdlib>
#include <iostream>
#include <stdexcept>
namespace {void require(bool v,const char*m){if(!v)throw std::runtime_error(m);}std::string d(char c){return std::string(64,c);}}
int main()try{using namespace genesis;using namespace genesis::learning;ConsolidationScheduler scheduler(5,4);require(scheduler.register_trace({"fact",TraceKind::declarative,.8,.3,.6,10,1,30,false}),"fact trace");require(scheduler.register_trace({"skill",TraceKind::procedural,.7,.2,.4,5,3,50,true}),"skill trace");require(scheduler.register_trace({"episode",TraceKind::episodic,.5,.8,.2,1,0,40,false}),"episode trace");require(!scheduler.register_trace({"fact",TraceKind::semantic,.1,.1,.1,0,0,1,false}),"duplicate trace accepted");require(scheduler.record_interference({"fact","episode",.9,d('a')}),"interference record");require(!scheduler.record_interference({"episode","fact",.5,d('b')}),"reverse duplicate interference accepted");require(!scheduler.record_interference({"missing","fact",.5,d('c')}),"missing trace interference accepted");auto first=scheduler.plan(100,70,3);require(first.reserved<=70&&first.items.size()==2&&!first.deferred.empty(),"bounded consolidation plan");require(first.items.front().trace_id=="episode","uncertainty and interference priority not applied deterministically");auto repeated=scheduler.plan(100,70,3);require(first.items[0].trace_id==repeated.items[0].trace_id&&first.items[1].trace_id==repeated.items[1].trace_id,"same inputs changed plan");require(scheduler.record_use("episode",101),"record trace use");require(!scheduler.record_use("episode",100),"time reversal accepted");require(scheduler.verify(),"learning scheduler invariants");
memory::MemoryGraph graph("organism",5,2);auto node=[](std::string id){return memory::MemoryNode{std::move(id),"organism",d('1'),d('2'),"learning",memory::MemoryKind::fact,memory::Origin::direct_experience,memory::IdentityScope::organism_private,memory::ActivationState::available,.5,.2,0,1,1,0,{"trace"}};};require(graph.add(node("episode"))&&graph.add(node("fact")),"executor memory setup");runtime::ResourceAccounts resources{{{"consolidation_units",70}}};ConsolidationExecutor executor(2);const auto applied=executor.execute(first,graph,resources);require(applied.applied()&&graph.find("episode")->strength>.2&&graph.find("fact")->strength>.2,"atomic consolidation did not apply");require(executor.records().size()==1&&executor.records()[0].changes.size()==2&&executor.verify(),"consolidation audit chain invalid");require(resources.snapshot("consolidation_units")->current==0,"transient consolidation resources leaked");
const auto before=memory::MemoryGraph::state_digest(*graph.find("episode"));runtime::ResourceAccounts denied{{{"consolidation_units",1}}};require(executor.execute(first,graph,denied).status==ConsolidationStatus::resource_denied&&memory::MemoryGraph::state_digest(*graph.find("episode"))==before,"resource denial changed memory");auto invalid=first;invalid.items.push_back(invalid.items.front());invalid.reserved+=invalid.items.back().reserved_cost;invalid.budget=invalid.reserved;require(executor.execute(invalid,graph,resources).status==ConsolidationStatus::invalid_plan&&memory::MemoryGraph::state_digest(*graph.find("episode"))==before,"invalid plan changed memory");std::vector<memory::ReinforcementRequest> stale{{"episode",.1,d('f')},{"fact",.1,memory::MemoryGraph::state_digest(*graph.find("fact"))}};require(!graph.reinforce_batch(stale,200)&&memory::MemoryGraph::state_digest(*graph.find("episode"))==before,"stale batch was not atomic");
RetentionEvaluator retention(5);require(retention.observe({"episode",d('3'),{},TraceKind::episodic,110,.9,.8,.9,{}}),"retention baseline rejected");require(!retention.report("episode"),"single observation produced outcome");require(retention.observe({"episode",d('4'),applied.record_digest,TraceKind::episodic,300,.4,.5,.8,{"fact"}}),"retention follow-up rejected");const auto report=retention.report("episode");require(report&&report->trend==RetentionTrend::regressed&&report->delta<0&&report->retention_ratio&&*report->retention_ratio<1&&report->elapsed==190&&report->consolidation_observed&&report->interference_associated,"retention regression not measured");const auto feedback=retention.feedback("episode");require(feedback&&feedback->urgency>0&&feedback->accessibility_adjustment<0&&feedback->uncertainty_adjustment>0,"retention feedback invalid");require(scheduler.apply_feedback(*feedback),"scheduler rejected valid retention feedback");require(!retention.observe({"episode",d('5'),{},TraceKind::episodic,300,.8,.8,.8,{}}),"non-advancing retention evidence accepted");require(!retention.observe({"fact",d('6'),{},TraceKind::declarative,400,.8,.8,.8,{"episode","episode"}}),"duplicate interference attribution accepted");require(retention.verify()&&retention.records().size()==2,"retention evidence chain invalid");RetentionEvaluator bounded(1);require(!bounded.observe({"bad","short",{},TraceKind::semantic,1,.5,.5,.5,{}}),"invalid evidence digest accepted");require(bounded.observe({"zero",d('7'),{},TraceKind::semantic,1,0,0,.5,{}})&&!bounded.observe({"zero",d('8'),{},TraceKind::semantic,2,.5,.5,.5,{}}),"retention capacity was not enforced");
std::cout<<"learning tests passed\n";return EXIT_SUCCESS;}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return EXIT_FAILURE;}
