#include "genesis/cognition/workspace.hpp"
#include "genesis/cognition/persistence.hpp"
#include "genesis/cognition/world_model.hpp"
#include "genesis/cognition/world_persistence.hpp"
#include "genesis/memory/graph.hpp"
#include "genesis/memory/persistence.hpp"
#include "genesis/runtime/runtime.hpp"
#include <cstdlib>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <stdexcept>
namespace { void require(bool v,const char*m){if(!v)throw std::runtime_error(m);} std::string d(char c){return std::string(64,c);} }
int main()try{
 using namespace genesis::memory;
 MemoryGraph graph("genesis",8,12);
 MemoryNode positive{"party-positive","genesis",d('a'),d('b'),"positive",MemoryKind::episode,Origin::direct_experience,IdentityScope::organism_private,ActivationState::available,.8,.9,.7,1,1,1,{"party","music","friends"}};
 MemoryNode negative{"party-negative","genesis",d('c'),d('d'),"negative",MemoryKind::episode,Origin::direct_experience,IdentityScope::organism_private,ActivationState::available,.7,.6,-.5,2,2,1,{"party","crowd","unknown"}};
 require(graph.add(positive)&&graph.add(negative),"add scoped memories");
 require(graph.connect({"party-positive","party-negative",.2,"same-event-class"}),"connect memories");
 MemoryNode pattern{"party-pattern","genesis",d('9'),d('8'),"mixed",MemoryKind::pattern,Origin::inferred,IdentityScope::organism_private,ActivationState::available,.6,.5,0,3,3,0,{"pattern-only"}};require(graph.add(pattern),"add related pattern");require(graph.connect({"party-negative","party-pattern",.5,"same-event-class"}),"connect transitive memory");auto related=graph.related("party-positive","same-event-class",2,4);require(related.size()==2&&related[1].depth==2&&related[1].path_weight==.1,"bounded relationship traversal");
 auto activated=graph.activate({"party","music"},"birthday",4);require(activated.size()==2&&activated[0].id=="party-positive","associative activation");
 require(graph.activate({"never-seen"},"unmatched",4).empty(),"unmatched features activated unrelated memories");
 auto predictions=graph.predict({"party","music"},"birthday",4);require(!predictions.empty(),"experience prediction");
 require(graph.decay(.5,.1)&&graph.find("party-negative")->state==ActivationState::dormant,"declarative decay");
 require(graph.reinforce("party-negative",.5,10)&&graph.find("party-negative")->state==ActivationState::available,"relearning trace recovery");
 require(graph.consolidate("party-positive")&&graph.verify(),"consolidation and graph verification");
 const auto bytes=MemoryStore::serialize(graph); MemoryStoreError store_error;
 auto decoded=MemoryStore::deserialize(bytes,&store_error);require(decoded&&decoded->verify()&&decoded->size()==3&&decoded->related("party-positive","same-event-class",2,4).size()==2,"memory serialization round trip");
 auto corrupt=bytes;corrupt[corrupt.size()/2]^=1;require(!MemoryStore::deserialize(corrupt,&store_error)&&store_error.code==MemoryStoreErrorCode::corrupt_record,"corrupt memory accepted");
 const auto root=std::filesystem::temp_directory_path()/"genesis-memory-store-v1";std::error_code cleanup;std::filesystem::remove_all(root,cleanup);MemoryStore store(root);
 require(store.write(graph,"1.0.0",&store_error),"memory store write");auto restored=store.read("genesis","1.0.0",&store_error);require(restored&&restored->verify(),"memory store restore");
 require(store.write(graph,"1.0.0",&store_error),"idempotent memory write");MemoryGraph conflicting("genesis",8,12);require(conflicting.add(positive),"conflict graph setup");require(!store.write(conflicting,"1.0.0",&store_error)&&store_error.code==MemoryStoreErrorCode::conflicting_version,"immutable memory version conflict accepted");
 require(!store.read("../escape","1.0.0",&store_error)&&store_error.code==MemoryStoreErrorCode::invalid_identifier,"unsafe memory path accepted");std::filesystem::remove_all(root,cleanup);
 using namespace genesis::cognition;
 BeliefModel models("genesis",8); require(models.update({"world-1","room occupied",d('e'),ModelKind::world,.8,.2,1,"room-occupied",true,BeliefState::active,{},"camera-1",.9}),"world belief");require(!models.update({"world-1","replacement",d('e'),ModelKind::world,.8,.2,2,"room-occupied",true,BeliefState::active,{},"camera-1",.9}),"duplicate belief event replaced history"); require(models.update({"self-1","energy constrained",d('f'),ModelKind::self,.7,.3,1,"self-energy",true,BeliefState::active,{},"metabolism",1}),"self belief");
 require(models.update({"world-2","room unoccupied",d('6'),ModelKind::world,.75,.25,2,"room-occupied",false,BeliefState::active,{},"camera-2",.7}),"contradicting belief");require(models.contradictions("room-occupied").size()==2,"contradiction set");require(models.update({"world-3","verified room state",d('7'),ModelKind::world,.95,.05,3,"room-occupied",true,BeliefState::active,"world-1","validated-sensor",1}),"belief supersession");require(models.find("world-1")->state==BeliefState::superseded,"superseded belief remained active");require(models.retract("world-2",d('5'),4)&&models.contradictions("room-occupied").empty(),"belief retraction");require(models.assessed_confidence("world-3",3,10)&&*models.assessed_confidence("world-3",3,10)==.95&&models.verify(),"belief source quality or freshness assessment failed");
 auto belief_bytes=BeliefStore::serialize(models);BeliefStoreError belief_error;auto belief_copy=BeliefStore::deserialize(belief_bytes,&belief_error);require(belief_copy&&belief_copy->verify()&&belief_copy->find("world-1")->state==BeliefState::superseded&&belief_copy->find("world-2")->state==BeliefState::retracted,"belief model roundtrip failed");auto belief_corrupt=belief_bytes;belief_corrupt[belief_corrupt.size()/2]^=1;require(!BeliefStore::deserialize(belief_corrupt,&belief_error)&&belief_error.code==BeliefStoreErrorCode::corrupt_record,"corrupt belief snapshot accepted");auto belief_future=belief_bytes;belief_future[std::string_view{"GENESIS-BELIEF"}.size()]=2;belief_future.replace(belief_future.size()-64,64,genesis::runtime::sha256(std::string_view{belief_future}.substr(0,belief_future.size()-64)));require(!BeliefStore::deserialize(belief_future,&belief_error)&&belief_error.code==BeliefStoreErrorCode::unsupported_schema,"unsupported belief schema accepted");const auto belief_root=std::filesystem::temp_directory_path()/"genesis-belief-store-v1";std::filesystem::remove_all(belief_root,cleanup);BeliefStore belief_store(belief_root);require(belief_store.write(models,"1.0.0",&belief_error)&&belief_store.write(models,"1.0.0",&belief_error),"belief store idempotent write failed");auto belief_conflict=models;require(belief_conflict.update({"other-1","agent available",d('4'),ModelKind::other_agent,.6,.4,5,"agent-available",true,BeliefState::active,{},"network-observation",.6})&&!belief_store.write(belief_conflict,"1.0.0",&belief_error)&&belief_error.code==BeliefStoreErrorCode::conflicting_version,"conflicting belief version accepted");require(!belief_store.read("../escape","1.0.0",&belief_error)&&belief_error.code==BeliefStoreErrorCode::invalid_identifier,"unsafe belief path accepted");auto belief_restored=belief_store.read("genesis","1.0.0",&belief_error);require(belief_restored&&belief_restored->verify(),"belief store recovery failed");std::filesystem::remove_all(belief_root,cleanup);
 WorldDynamics dynamics("genesis",8,4,8);require(dynamics.observe_state({"obs-1","room","temperature",d('a'),d('b'),10,.9}),"world state observation");require(!dynamics.observe_state({"obs-1","room","temperature",d('a'),d('b'),11,.9}),"duplicate state observation accepted");require(dynamics.register_hypothesis({"heat-causes-fan","temperature",d('a'),"fan-state",d('c'),d('d'),10,10,0,0,.6,.6}),"causal hypothesis");require(dynamics.issue_prediction({"prediction-1","heat-causes-fan","room",d('c'),{},11,20,0,.6,PredictionState::pending}),"world prediction");require(dynamics.resolve_prediction("prediction-1",d('c'),d('e'),15),"prediction confirmation");require(dynamics.find_prediction("prediction-1")->state==PredictionState::confirmed&&dynamics.find_hypothesis("heat-causes-fan")->support_count==1&&dynamics.find_hypothesis("heat-causes-fan")->calibrated_confidence>.6,"causal confirmation calibration");require(dynamics.issue_prediction({"prediction-2","heat-causes-fan","room",d('c'),{},16,25,0,.7,PredictionState::pending})&&dynamics.resolve_prediction("prediction-2",d('f'),d('1'),20),"prediction refutation");require(dynamics.find_prediction("prediction-2")->state==PredictionState::refuted&&dynamics.find_hypothesis("heat-causes-fan")->counterevidence_count==1,"causal counterevidence missing");require(dynamics.issue_prediction({"prediction-3","heat-causes-fan","room",d('c'),{},21,22,0,.5,PredictionState::pending})&&dynamics.expire_predictions(23)==1&&dynamics.find_prediction("prediction-3")->state==PredictionState::expired,"prediction expiry failed");auto alternatives=dynamics.simulate("temperature",d('a'),4);require(alternatives.size()==1&&alternatives[0].simulated&&alternatives[0].hypothesis_id=="heat-causes-fan"&&dynamics.verify(),"bounded counterfactual simulation failed");
 WorldDynamics causal_graph("genesis",4,8,4);require(causal_graph.register_hypothesis({"a-b","a",d('a'),"b",d('b'),d('1'),1,1,0,0,.9,.9})&&causal_graph.register_hypothesis({"b-c","b",d('b'),"c",d('c'),d('2'),1,1,0,0,.8,.8})&&causal_graph.register_hypothesis({"c-a","c",d('c'),"a",d('a'),d('3'),1,1,0,0,.7,.7})&&causal_graph.register_hypothesis({"a-d","a",d('a'),"d",d('d'),d('4'),1,1,0,0,.6,.6}),"counterfactual graph setup");
 const auto before_hypotheses=causal_graph.hypothesis_count(),before_states=causal_graph.state_count();auto paths=causal_graph.simulate_intervention({"a",d('a')},{3,4,8,16,0});require(paths.paths.size()==3&&paths.paths[0].steps.size()==1&&paths.paths[0].steps[0].hypothesis_id=="a-b"&&paths.paths[1].steps.size()==2&&paths.paths[1].final_property=="c"&&paths.paths[1].unresolved_confounders&&std::abs(paths.paths[1].accumulated_confidence-.72)<1e-12&&paths.paths[2].steps[0].hypothesis_id=="a-d","deterministic confidence-ranked multi-step search failed");require(paths.paths[0].simulated&&!paths.paths[0].action_authorized&&paths.paths[0].unresolved_confounders&&causal_graph.hypothesis_count()==before_hypotheses&&causal_graph.state_count()==before_states,"simulation mutated facts or granted authority");
 auto repeated=causal_graph.simulate_intervention({"a",d('a')},{3,4,8,16,0});require(repeated.paths.size()==paths.paths.size()&&repeated.paths[1].steps[1].hypothesis_id==paths.paths[1].steps[1].hypothesis_id,"counterfactual order changed");require(paths.paths.size()==3,"cycle was not prevented");
 auto depth_limited=causal_graph.simulate_intervention({"a",d('a')},{1,4,8,16,0});require(depth_limited.depth_limited&&depth_limited.paths.size()==2,"depth truncation not reported");auto branch_limited=causal_graph.simulate_intervention({"a",d('a')},{3,1,8,16,0});require(branch_limited.branch_limited&&branch_limited.paths.size()==2,"branch truncation not reported");auto path_limited=causal_graph.simulate_intervention({"a",d('a')},{3,4,1,16,0});require(path_limited.path_limited&&path_limited.paths.size()==1,"path truncation not reported");auto budget_limited=causal_graph.simulate_intervention({"a",d('a')},{3,4,8,1,0});require(budget_limited.budget_exhausted&&budget_limited.expanded_nodes==1,"expansion budget not reported");auto confidence_pruned=causal_graph.simulate_intervention({"a",d('a')},{3,4,8,16,.85});require(confidence_pruned.paths.size()==1&&confidence_pruned.paths[0].final_property=="b","minimum confidence pruning failed");require(causal_graph.simulate_intervention({"",d('a')},{3,4,8,16,0}).paths.empty()&&causal_graph.simulate_intervention({"a",d('a')},{0,4,8,16,0}).paths.empty(),"invalid simulation input accepted");
 auto causal_copy=WorldDynamicsStore::deserialize(WorldDynamicsStore::serialize(causal_graph));require(causal_copy&&causal_copy->simulate_intervention({"a",d('a')},{3,4,8,16,0}).paths.size()==paths.paths.size(),"multi-step simulation was not reproducible after recovery");
 auto world_bytes=WorldDynamicsStore::serialize(dynamics);WorldStoreError world_error;auto dynamics_copy=WorldDynamicsStore::deserialize(world_bytes,&world_error);require(dynamics_copy&&dynamics_copy->verify()&&dynamics_copy->find_prediction("prediction-1")->state==PredictionState::confirmed&&dynamics_copy->find_prediction("prediction-2")->state==PredictionState::refuted&&dynamics_copy->find_prediction("prediction-3")->state==PredictionState::expired,"world dynamics roundtrip failed");auto world_corrupt=world_bytes;world_corrupt[world_corrupt.size()/2]^=1;require(!WorldDynamicsStore::deserialize(world_corrupt,&world_error)&&world_error.code==WorldStoreErrorCode::corrupt_record,"corrupt world snapshot accepted");auto world_future=world_bytes;world_future[std::string_view{"GENESIS-WORLD-DYNAMICS"}.size()]=2;world_future.replace(world_future.size()-64,64,genesis::runtime::sha256(std::string_view{world_future}.substr(0,world_future.size()-64)));require(!WorldDynamicsStore::deserialize(world_future,&world_error)&&world_error.code==WorldStoreErrorCode::unsupported_schema,"unsupported world schema accepted");const auto world_root=std::filesystem::temp_directory_path()/"genesis-world-store-v1";std::filesystem::remove_all(world_root,cleanup);WorldDynamicsStore world_store(world_root);require(world_store.write(dynamics,"1.0.0",&world_error)&&world_store.write(dynamics,"1.0.0",&world_error),"world store idempotent write failed");auto dynamics_conflict=dynamics;require(dynamics_conflict.observe_state({"obs-2","room","humidity",d('2'),d('3'),24,.8})&&!world_store.write(dynamics_conflict,"1.0.0",&world_error)&&world_error.code==WorldStoreErrorCode::conflicting_version,"conflicting world version accepted");require(!world_store.read("../escape","1.0.0",&world_error)&&world_error.code==WorldStoreErrorCode::invalid_identifier,"unsafe world path accepted");auto world_restored=world_store.read("genesis","1.0.0",&world_error);require(world_restored&&world_restored->verify(),"world store recovery failed");std::filesystem::remove_all(world_root,cleanup);
 ConsciousWorkspace workspace(2);require(workspace.submit({"candidate-1","memory",d('1'),.9,.8,false,2}),"workspace candidate");require(workspace.submit({"candidate-2","perception",d('2'),.8,.9,false,1}),"workspace perception");require(workspace.submit({"candidate-3","reflex",d('3'),1,1,true,1}),"inhibited candidate");
 auto report=workspace.introspect();require(report.admitted==2&&report.inhibited==0&&report.uncertainty>0,"bounded introspection");
 std::cout<<"memory and cognition tests passed\n";return EXIT_SUCCESS;
}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return EXIT_FAILURE;}
