#include "genesis/learning/consolidation.hpp"
#include <algorithm>
#include <bit>
#include <cmath>
#include <set>
#include <sstream>
#include <stdexcept>
namespace genesis::learning { namespace { bool text(std::string_view s){return !s.empty()&&s.size()<=256&&std::all_of(s.begin(),s.end(),[](unsigned char c){return c>=0x20&&c!=0x7f;});}bool ratio(double v){return std::isfinite(v)&&v>=0&&v<=1;}bool digest(std::string_view s){return s.size()==64&&std::all_of(s.begin(),s.end(),[](unsigned char c){return std::isxdigit(c)!=0;});}}
ConsolidationScheduler::ConsolidationScheduler(std::size_t tc,std::size_t ic):trace_capacity_(tc),interference_capacity_(ic){if(!tc||!ic)throw std::invalid_argument("consolidation capacities must be positive");}
bool ConsolidationScheduler::register_trace(LearningTrace t,std::string*e){if(e)e->clear();if(traces_.size()>=trace_capacity_||!text(t.id)||traces_.contains(t.id)||!ratio(t.importance)||!ratio(t.uncertainty)||!ratio(t.accessibility)||!t.estimated_cost){if(e)*e="invalid duplicate or over-capacity learning trace";return false;}traces_.emplace(t.id,std::move(t));return true;}
bool ConsolidationScheduler::record_interference(InterferenceEdge x,std::string*e){if(e)e->clear();if(interference_.size()>=interference_capacity_||x.first==x.second||!traces_.contains(x.first)||!traces_.contains(x.second)||!ratio(x.severity)||x.severity==0||!digest(x.evidence_digest)){if(e)*e="invalid interference evidence";return false;}if(x.second<x.first)std::swap(x.first,x.second);if(std::any_of(interference_.begin(),interference_.end(),[&](const auto&y){return y.first==x.first&&y.second==x.second;})){if(e)*e="duplicate interference pair";return false;}interference_.push_back(std::move(x));return true;}
bool ConsolidationScheduler::record_use(std::string_view id,std::uint64_t now){auto it=traces_.find(std::string(id));if(it==traces_.end()||now<it->second.last_used||it->second.rehearsal_count==UINT64_MAX)return false;it->second.last_used=now;++it->second.rehearsal_count;it->second.accessibility=std::min(1.0,it->second.accessibility+.05);return true;}
bool ConsolidationScheduler::apply_feedback(const RetentionFeedback&f,std::string*e){if(e)e->clear();auto it=traces_.find(f.trace_id);if(it==traces_.end()||!std::isfinite(f.accessibility_adjustment)||std::abs(f.accessibility_adjustment)>.25||!std::isfinite(f.uncertainty_adjustment)||std::abs(f.uncertainty_adjustment)>.25||!ratio(f.urgency)||f.observed_at<it->second.last_used){if(e)*e="invalid stale or unknown retention feedback";return false;}it->second.accessibility=std::clamp(it->second.accessibility+f.accessibility_adjustment,0.0,1.0);it->second.uncertainty=std::clamp(it->second.uncertainty+f.uncertainty_adjustment,0.0,1.0);return true;}
ConsolidationPlan ConsolidationScheduler::plan(std::uint64_t now,std::uint64_t budget,std::size_t maximum)const{ConsolidationPlan result{now,budget,0,{},{}};struct Candidate{const LearningTrace*t;double priority;std::vector<std::string> conflicts;};std::vector<Candidate> candidates;for(const auto&[id,t]:traces_){double pressure=0;std::vector<std::string> conflicts;for(const auto&x:interference_){if(x.first==id){pressure=std::max(pressure,x.severity);conflicts.push_back(x.second);}else if(x.second==id){pressure=std::max(pressure,x.severity);conflicts.push_back(x.first);}}const double age=now>=t.last_used?std::min(1.0,static_cast<double>(now-t.last_used)/1000.0):0;const double kind=t.kind==TraceKind::procedural?.15:0;const double priority=std::clamp(t.importance*.35+t.uncertainty*.2+(1-t.accessibility)*.15+pressure*.15+age*.1+kind,0.0,1.0);candidates.push_back({&t,priority,std::move(conflicts)});}std::sort(candidates.begin(),candidates.end(),[](const auto&a,const auto&b){return a.priority!=b.priority?a.priority>b.priority:a.t->id<b.t->id;});for(const auto&c:candidates){if(result.items.size()>=maximum){result.deferred.push_back(c.t->id);continue;}if(c.t->estimated_cost>budget-result.reserved){result.deferred.push_back(c.t->id);continue;}result.items.push_back({c.t->id,c.priority,c.t->estimated_cost,c.conflicts});result.reserved+=c.t->estimated_cost;}return result;}
bool ConsolidationScheduler::verify()const{if(traces_.size()>trace_capacity_||interference_.size()>interference_capacity_)return false;std::set<std::pair<std::string,std::string>> pairs;for(const auto&[id,t]:traces_)if(id!=t.id||!ratio(t.importance)||!ratio(t.uncertainty)||!ratio(t.accessibility)||!t.estimated_cost)return false;for(const auto&x:interference_)if(!traces_.contains(x.first)||!traces_.contains(x.second)||x.first>=x.second||!ratio(x.severity)||!pairs.emplace(x.first,x.second).second)return false;return true;}
std::size_t ConsolidationScheduler::trace_count()const noexcept{return traces_.size();}
namespace {double retention_score(const RetentionObservation&o){return o.recall_score*.7+o.latency_score*.3;}std::string retention_material(const RetentionRecord&r){std::ostringstream o;o<<r.sequence<<'|'<<r.observation.trace_id<<'|'<<static_cast<unsigned>(r.observation.kind)<<'|'<<r.observation.logical_time<<'|'<<std::bit_cast<std::uint64_t>(r.observation.recall_score)<<'|'<<std::bit_cast<std::uint64_t>(r.observation.latency_score)<<'|'<<std::bit_cast<std::uint64_t>(r.observation.confidence)<<'|'<<r.observation.evidence_digest<<'|'<<r.observation.consolidation_record_digest<<'|'<<r.previous_digest;for(const auto&id:r.observation.active_interference_ids)o<<'|'<<id;return o.str();}}
RetentionEvaluator::RetentionEvaluator(std::string organism,std::size_t capacity,double tolerance):organism_id_(std::move(organism)),record_capacity_(capacity),stable_tolerance_(tolerance){if(!text(organism_id_)||!capacity||!std::isfinite(tolerance)||tolerance<0||tolerance>.25)throw std::invalid_argument("invalid retention evaluator identity or limits");records_.reserve(capacity);}
bool RetentionEvaluator::observe(RetentionObservation o,std::string*e){if(e)e->clear();auto fail=[&](const char*m){if(e)*e=m;return false;};if(records_.size()>=record_capacity_||!text(o.trace_id)||static_cast<unsigned>(o.kind)>static_cast<unsigned>(TraceKind::semantic)||!digest(o.evidence_digest)||(!o.consolidation_record_digest.empty()&&!digest(o.consolidation_record_digest))||!ratio(o.recall_score)||!ratio(o.latency_score)||!ratio(o.confidence))return fail("invalid or over-capacity retention observation");std::set<std::string> unique;for(const auto&id:o.active_interference_ids)if(!text(id)||id==o.trace_id||!unique.insert(id).second)return fail("invalid retention interference identifiers");const auto indexed=trace_index_.find(o.trace_id);if(indexed!=trace_index_.end()){const auto&previous=records_[indexed->second.back()].observation;if(o.logical_time<=previous.logical_time||o.kind!=previous.kind)return fail("non-advancing or conflicting retention observation");}RetentionRecord r{records_.size()+1,std::move(o),records_.empty()?std::string(64,'0'):records_.back().digest,{}};r.digest=runtime::sha256(retention_material(r));records_.push_back(std::move(r));trace_index_[records_.back().observation.trace_id].push_back(records_.size()-1);return true;}
std::optional<RetentionReport> RetentionEvaluator::report(std::string_view id)const{const auto it=trace_index_.find(std::string(id));if(it==trace_index_.end()||it->second.size()<2)return std::nullopt;const auto&base=records_[it->second.front()].observation;const auto&last=records_[it->second.back()].observation;const double before=retention_score(base),after=retention_score(last),delta=after-before;RetentionTrend trend=delta>stable_tolerance_?RetentionTrend::improved:(delta< -stable_tolerance_?RetentionTrend::regressed:RetentionTrend::stable);const std::optional<double> ratio_value=before>0?std::optional<double>{after/before}:std::nullopt;return RetentionReport{last.trace_id,last.kind,base.logical_time,last.logical_time,last.logical_time-base.logical_time,before,after,delta,ratio_value,trend,!last.consolidation_record_digest.empty(),trend==RetentionTrend::regressed&&!last.active_interference_ids.empty(),last.active_interference_ids};}
std::optional<RetentionFeedback> RetentionEvaluator::feedback(std::string_view id)const{const auto r=report(id);if(!r)return std::nullopt;const double access=std::clamp(r->delta,-.25,.25);const double uncertainty=r->trend==RetentionTrend::regressed?.2:(r->trend==RetentionTrend::improved?-.1:0);const double urgency=r->trend==RetentionTrend::regressed?std::clamp(-r->delta+(r->interference_associated?.2:0),0.0,1.0):0;return RetentionFeedback{r->trace_id,access,uncertainty,urgency,r->follow_up_time};}
bool RetentionEvaluator::verify()const{if(records_.size()>record_capacity_)return false;std::string previous(64,'0');std::uint64_t sequence=1;std::map<std::string,std::uint64_t> times;std::map<std::string,std::vector<std::size_t>> expected_index;for(std::size_t index=0;index<records_.size();++index){const auto&r=records_[index];if(r.sequence!=sequence++||r.previous_digest!=previous||r.digest!=runtime::sha256(retention_material(r))||static_cast<unsigned>(r.observation.kind)>static_cast<unsigned>(TraceKind::semantic)||!digest(r.observation.evidence_digest)||!ratio(r.observation.recall_score)||!ratio(r.observation.latency_score)||!ratio(r.observation.confidence))return false;const auto found=times.find(r.observation.trace_id);if(found!=times.end()&&r.observation.logical_time<=found->second)return false;times[r.observation.trace_id]=r.observation.logical_time;expected_index[r.observation.trace_id].push_back(index);previous=r.digest;}return expected_index==trace_index_;}
const std::vector<RetentionRecord>& RetentionEvaluator::records()const noexcept{return records_;}
const std::string& RetentionEvaluator::organism_id()const noexcept{return organism_id_;}
std::size_t RetentionEvaluator::record_capacity()const noexcept{return record_capacity_;}
double RetentionEvaluator::stable_tolerance()const noexcept{return stable_tolerance_;}
ConsolidationExecutor::ConsolidationExecutor(std::size_t capacity,double scale):record_capacity_(capacity),reinforcement_scale_(scale){if(!capacity||!std::isfinite(scale)||scale<=0||scale>1)throw std::invalid_argument("invalid consolidation executor limits");records_.reserve(capacity);}
namespace {std::string record_material(const ConsolidationRecord&r){std::ostringstream o;o<<r.sequence<<'|'<<r.logical_time<<'|'<<r.reserved_cost<<'|'<<r.organism_id<<'|'<<r.previous_digest;for(const auto&c:r.changes)o<<'|'<<c.id<<'|'<<c.before_state_digest<<'|'<<c.after_state_digest;return o.str();}}
ConsolidationOutcome ConsolidationExecutor::execute(const ConsolidationPlan&p,memory::MemoryGraph&g,runtime::ResourceAccounts&resources){auto out=[](ConsolidationStatus s,std::string m,std::string d={}){return ConsolidationOutcome{s,std::move(m),std::move(d)};};if(records_.size()>=record_capacity_)return out(ConsolidationStatus::record_capacity_exceeded,"consolidation record capacity exceeded");if(p.items.empty()||!p.reserved||p.reserved>p.budget)return out(ConsolidationStatus::invalid_plan,"empty or inconsistent consolidation plan");std::uint64_t sum=0;std::set<std::string> ids;std::vector<memory::ReinforcementRequest> requests;for(const auto&i:p.items){if(i.trace_id.empty()||!i.reserved_cost||sum>p.reserved||i.reserved_cost>p.reserved-sum||!std::isfinite(i.priority)||i.priority<0||i.priority>1||!ids.insert(i.trace_id).second)return out(ConsolidationStatus::invalid_plan,"invalid duplicate or overflowing consolidation item");sum+=i.reserved_cost;const auto*n=g.find(i.trace_id);if(!n)return out(ConsolidationStatus::stale_memory,"planned trace is absent from memory");requests.push_back({i.trace_id,std::max(.01,i.priority*reinforcement_scale_),memory::MemoryGraph::state_digest(*n)});}if(sum!=p.reserved)return out(ConsolidationStatus::invalid_plan,"plan reservation does not equal item costs");runtime::ReservationError resource_error;auto reservation=resources.try_reserve({{"consolidation_units",p.reserved}},&resource_error);if(!reservation||!reservation->commit())return out(ConsolidationStatus::resource_denied,"consolidation resource reservation denied");std::vector<memory::ReinforcementChange> changes;std::string error;if(!g.reinforce_batch(requests,p.logical_time,&changes,&error)){static_cast<void>(reservation->release());return out(ConsolidationStatus::stale_memory,error);}ConsolidationRecord record{records_.size()+1,p.logical_time,p.reserved,g.organism_id(),records_.empty()?std::string(64,'0'):records_.back().digest,{},std::move(changes)};record.digest=runtime::sha256(record_material(record));static_cast<void>(reservation->release());records_.push_back(std::move(record));return out(ConsolidationStatus::applied,{},records_.back().digest);}
bool ConsolidationExecutor::verify()const{if(records_.size()>record_capacity_)return false;std::string previous(64,'0');std::uint64_t sequence=1;for(const auto&r:records_){if(r.sequence!=sequence++||r.previous_digest!=previous||r.digest!=runtime::sha256(record_material(r))||r.changes.empty())return false;previous=r.digest;}return true;}
const std::vector<ConsolidationRecord>& ConsolidationExecutor::records()const noexcept{return records_;}
}
