#include "genesis/learning/persistence.hpp"
#include "genesis/runtime/runtime.hpp"
#include <bit>
#include <cctype>
#include <fstream>
#include <iterator>
#include <stdexcept>
#include <system_error>

namespace genesis::learning { namespace {
constexpr std::string_view magic="GENESIS-RETENTION";constexpr std::uint64_t schema=1,max_items=1000000,max_field=16U*1024U*1024U;
void err(RetentionStoreError*e,RetentionStoreErrorCode c,std::string m){if(e){e->code=c;e->message=std::move(m);}}
void id_ok(std::string_view s){if(s.empty()||s.size()>128||s=="."||s=="..")throw std::invalid_argument("unsafe identifier");for(unsigned char c:s)if(!std::isalnum(c)&&c!='_'&&c!='-'&&c!='.')throw std::invalid_argument("unsafe identifier character");}
void u64(std::string&o,std::uint64_t v){for(unsigned s=0;s<64;s+=8)o.push_back(static_cast<char>((v>>s)&255));}
std::uint64_t get64(std::string_view b,std::size_t&o){if(o>b.size()||b.size()-o<8)throw std::runtime_error("truncated integer");std::uint64_t v=0;for(unsigned s=0;s<64;s+=8)v|=static_cast<std::uint64_t>(static_cast<unsigned char>(b[o++]))<<s;return v;}
void str(std::string&o,std::string_view s){u64(o,s.size());o.append(s);}
std::string getstr(std::string_view b,std::size_t&o){const auto n=get64(b,o);if(n>max_field||n>b.size()-o)throw std::runtime_error("invalid field length");std::string s(b.substr(o,n));o+=n;return s;}
void strings(std::string&o,const std::vector<std::string>&v){if(v.size()>max_items)throw std::invalid_argument("too many strings");u64(o,v.size());for(const auto&s:v)str(o,s);}
std::vector<std::string> getstrings(std::string_view b,std::size_t&o){auto n=get64(b,o);if(n>max_items)throw std::runtime_error("too many strings");std::vector<std::string>v;v.reserve(n);while(n--)v.push_back(getstr(b,o));return v;}
std::string readall(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("cannot open retention record");std::string b{std::istreambuf_iterator<char>(f),{}};if(f.bad())throw std::runtime_error("cannot read retention record");return b;}
}
RetentionStore::RetentionStore(std::filesystem::path root,std::size_t maximum):root_(std::move(root)),maximum_record_bytes_(maximum){if(root_.empty()||maximum<1024)throw std::invalid_argument("invalid retention store configuration");}
std::string RetentionStore::serialize(const RetentionEvaluator&e){if(!e.verify())throw std::invalid_argument("invalid retention evaluator");std::string o(magic);u64(o,schema);str(o,e.organism_id());u64(o,e.record_capacity());u64(o,std::bit_cast<std::uint64_t>(e.stable_tolerance()));u64(o,e.records().size());for(const auto&r:e.records()){const auto&x=r.observation;str(o,x.trace_id);str(o,x.evidence_digest);str(o,x.consolidation_record_digest);u64(o,static_cast<std::uint64_t>(x.kind));u64(o,x.logical_time);u64(o,std::bit_cast<std::uint64_t>(x.recall_score));u64(o,std::bit_cast<std::uint64_t>(x.latency_score));u64(o,std::bit_cast<std::uint64_t>(x.confidence));strings(o,x.active_interference_ids);}o+=runtime::sha256(o);return o;}
std::optional<RetentionEvaluator> RetentionStore::deserialize(std::string_view b,RetentionStoreError*e){try{if(b.size()<magic.size()+8+64||b.substr(0,magic.size())!=magic)throw std::runtime_error("invalid retention magic");const auto payload=b.substr(0,b.size()-64);if(runtime::sha256(payload)!=b.substr(b.size()-64))throw std::runtime_error("retention checksum mismatch");std::size_t o=magic.size();const auto stored_schema=get64(payload,o);if(stored_schema!=schema){err(e,RetentionStoreErrorCode::unsupported_schema,"unsupported retention schema");return std::nullopt;}auto owner=getstr(payload,o);const auto capacity=get64(payload,o);const auto tolerance=std::bit_cast<double>(get64(payload,o));if(!capacity||capacity>max_items)throw std::runtime_error("invalid retention capacity");RetentionEvaluator evaluator(owner,capacity,tolerance);auto count=get64(payload,o);if(count>capacity)throw std::runtime_error("retention count exceeds capacity");while(count--){RetentionObservation x;x.trace_id=getstr(payload,o);x.evidence_digest=getstr(payload,o);x.consolidation_record_digest=getstr(payload,o);const auto kind=get64(payload,o);if(kind>static_cast<std::uint64_t>(TraceKind::semantic))throw std::runtime_error("invalid retention kind");x.kind=static_cast<TraceKind>(kind);x.logical_time=get64(payload,o);x.recall_score=std::bit_cast<double>(get64(payload,o));x.latency_score=std::bit_cast<double>(get64(payload,o));x.confidence=std::bit_cast<double>(get64(payload,o));x.active_interference_ids=getstrings(payload,o);std::string reason;if(!evaluator.observe(std::move(x),&reason))throw std::runtime_error("invalid retention observation: "+reason);}if(o!=payload.size()||!evaluator.verify())throw std::runtime_error("trailing or invalid retention data");err(e,RetentionStoreErrorCode::none,{});return evaluator;}catch(const std::invalid_argument&x){err(e,RetentionStoreErrorCode::corrupt_record,x.what());return std::nullopt;}catch(const std::exception&x){err(e,RetentionStoreErrorCode::corrupt_record,x.what());return std::nullopt;}}
bool RetentionStore::write(const RetentionEvaluator&e,std::string_view version,RetentionStoreError*error)const{try{id_ok(e.organism_id());id_ok(version);auto bytes=serialize(e);if(bytes.size()>maximum_record_bytes_)throw std::invalid_argument("retention record exceeds configured limit");std::error_code ec;std::filesystem::create_directories(root_,ec);if(ec)throw std::runtime_error("cannot create retention store");const auto target=root_/(e.organism_id()+"."+std::string(version)+".retention");if(std::filesystem::exists(target)){if(readall(target)==bytes){err(error,RetentionStoreErrorCode::none,{});return true;}err(error,RetentionStoreErrorCode::conflicting_version,"immutable retention version conflict");return false;}const auto temporary=std::filesystem::path(target.string()+".tmp-"+runtime::sha256(bytes));{std::ofstream f(temporary,std::ios::binary|std::ios::trunc);f.write(bytes.data(),static_cast<std::streamsize>(bytes.size()));f.flush();if(!f)throw std::runtime_error("cannot flush retention record");}std::filesystem::rename(temporary,target,ec);if(ec){std::filesystem::remove(temporary);throw std::runtime_error("cannot atomically commit retention record");}err(error,RetentionStoreErrorCode::none,{});return true;}catch(const std::invalid_argument&x){err(error,RetentionStoreErrorCode::invalid_evaluator,x.what());return false;}catch(const std::exception&x){err(error,RetentionStoreErrorCode::io_error,x.what());return false;}}
std::optional<RetentionEvaluator> RetentionStore::read(std::string_view owner,std::string_view version,RetentionStoreError*error)const{try{id_ok(owner);id_ok(version);const auto path=root_/(std::string(owner)+"."+std::string(version)+".retention");if(!std::filesystem::exists(path)){err(error,RetentionStoreErrorCode::not_found,"retention record not found");return std::nullopt;}const auto bytes=readall(path);if(bytes.size()>maximum_record_bytes_){err(error,RetentionStoreErrorCode::corrupt_record,"retention record exceeds configured limit");return std::nullopt;}auto evaluator=deserialize(bytes,error);if(evaluator&&evaluator->organism_id()!=owner){err(error,RetentionStoreErrorCode::corrupt_record,"retention owner mismatch");return std::nullopt;}return evaluator;}catch(const std::invalid_argument&x){err(error,RetentionStoreErrorCode::invalid_identifier,x.what());return std::nullopt;}catch(const std::exception&x){err(error,RetentionStoreErrorCode::io_error,x.what());return std::nullopt;}}
}
