#include "genesis/perception/pipeline.hpp"
#include <algorithm>
#include <cctype>
#include <cmath>
#include <stdexcept>
#include <limits>
namespace genesis::perception {namespace {bool text(std::string_view s){return !s.empty()&&s.size()<=1024&&std::all_of(s.begin(),s.end(),[](unsigned char c){return c>=0x20&&c!=0x7f;});}bool digest(std::string_view s){return s.size()==64&&std::all_of(s.begin(),s.end(),[](unsigned char c){return std::isxdigit(c)!=0;});}bool ratio(double v){return std::isfinite(v)&&v>=0&&v<=1;}void fail(std::string*e,const char*m){if(e)*e=m;} }
PerceptionPipeline::PerceptionPipeline(std::string owner,std::size_t rc,std::size_t oc,std::size_t fc,QualificationPolicy p):organism_id_(std::move(owner)),route_capacity_(rc),observation_capacity_(oc),feature_capacity_(fc),policy_(p){if(!text(organism_id_)||!rc||!oc||!fc||!p.minimum_successes||!ratio(p.maximum_failure_rate))throw std::invalid_argument("invalid perception configuration");}
bool PerceptionPipeline::declare_route(AdapterRoute r,std::string*e){if(e)e->clear();if(routes_.size()>=route_capacity_||!text(r.id)||!text(r.provider_id)||!digest(r.artifact_digest)||!text(r.license_id)||!digest(r.declaration_evidence_digest)||r.state!=RouteEvidenceState::declared||r.probes||r.successes||r.failures||r.last_probe_at||!r.latest_probe_evidence_digest.empty()||!r.qualification_evidence_digest.empty()||static_cast<unsigned>(r.modality)>static_cast<unsigned>(Modality::custom)||routes_.contains(r.id)){fail(e,"invalid duplicate or over-capacity adapter route");return false;}routes_.emplace(r.id,std::move(r));return true;}
bool PerceptionPipeline::record_probe(std::string_view id,bool success,std::string_view evidence,std::uint64_t at,std::string*e){if(e)e->clear();auto it=routes_.find(std::string(id));if(it==routes_.end()||!digest(evidence)||at<it->second.last_probe_at||it->second.probes==std::numeric_limits<std::uint64_t>::max()||(success&&it->second.successes==std::numeric_limits<std::uint64_t>::max())||(!success&&it->second.failures==std::numeric_limits<std::uint64_t>::max())){fail(e,"invalid adapter probe");return false;}auto&r=it->second;++r.probes;if(success){++r.successes;if(r.state==RouteEvidenceState::declared)r.state=RouteEvidenceState::observed;}else ++r.failures;r.latest_probe_evidence_digest=std::string(evidence);r.last_probe_at=at;const double failure_rate=static_cast<double>(r.failures)/static_cast<double>(r.probes);if(r.state==RouteEvidenceState::qualified&&failure_rate>policy_.maximum_failure_rate){r.state=RouteEvidenceState::observed;r.qualification_evidence_digest.clear();}return true;}
bool PerceptionPipeline::qualify_route(std::string_view id,std::string_view evidence,std::uint64_t at,std::string*e){if(e)e->clear();auto it=routes_.find(std::string(id));if(it==routes_.end()||it->second.state!=RouteEvidenceState::observed||!digest(evidence)||at<it->second.last_probe_at||it->second.successes<policy_.minimum_successes||static_cast<double>(it->second.failures)/static_cast<double>(it->second.probes)>policy_.maximum_failure_rate){fail(e,"adapter route lacks qualification evidence");return false;}it->second.state=RouteEvidenceState::qualified;it->second.qualification_evidence_digest=std::string(evidence);it->second.last_probe_at=at;return true;}
bool PerceptionPipeline::ingest(RawObservation x,std::string*e){if(e)e->clear();const auto r=routes_.find(x.route_id);if(observations_.size()>=observation_capacity_||!text(x.id)||r==routes_.end()||r->second.state<RouteEvidenceState::observed||!digest(x.payload_digest)||!digest(x.provenance_digest)||x.received_at<x.captured_at||!ratio(x.confidence)||!ratio(x.uncertainty)||observations_.contains(x.id)){fail(e,"invalid unavailable or over-capacity observation");return false;}observations_.emplace(x.id,std::move(x));return true;}
bool PerceptionPipeline::derive(DerivedFeature x,std::string*e){if(e)e->clear();if(features_.size()>=feature_capacity_||!text(x.id)||!text(x.name)||!digest(x.value_digest)||!digest(x.derivation_digest)||!ratio(x.confidence)||!ratio(x.uncertainty)||!observations_.contains(x.observation_id)||features_.contains(x.id)){fail(e,"invalid duplicate or over-capacity derived feature");return false;}features_.emplace(x.id,std::move(x));return true;}
PerceptionProjection PerceptionPipeline::project(std::string_view id,std::size_t maximum)const{PerceptionProjection p;const auto*o=find_observation(id);if(!o||!maximum)return p;double confidence=o->confidence;std::size_t count=0;for(const auto&[_,f]:features_)if(f.observation_id==id&&count++<maximum)confidence=(confidence+f.confidence)/2;p.workspace_candidate=cognition::WorkspaceItem{"perception-"+o->id,"perception",o->payload_digest,std::clamp(confidence,0.0,1.0),confidence,false,o->received_at};p.memory_candidate=memory::MemoryNode{"perception-"+o->id,organism_id_,o->payload_digest,o->provenance_digest,"perception",memory::MemoryKind::observation,memory::Origin::observed,memory::IdentityScope::organism_private,memory::ActivationState::available,confidence,.5,0,o->received_at,o->received_at,0,{"perception",o->route_id}};return p;}
const AdapterRoute* PerceptionPipeline::find_route(std::string_view id)const noexcept{const auto it=routes_.find(std::string(id));return it==routes_.end()?nullptr:&it->second;}const RawObservation* PerceptionPipeline::find_observation(std::string_view id)const noexcept{const auto it=observations_.find(std::string(id));return it==observations_.end()?nullptr:&it->second;}
bool PerceptionPipeline::verify()const{if(!text(organism_id_)||!route_capacity_||!observation_capacity_||!feature_capacity_||!policy_.minimum_successes||!ratio(policy_.maximum_failure_rate)||routes_.size()>route_capacity_||observations_.size()>observation_capacity_||features_.size()>feature_capacity_)return false;for(const auto&[id,r]:routes_){if(id!=r.id||!text(r.id)||!text(r.provider_id)||!digest(r.artifact_digest)||!text(r.license_id)||!digest(r.declaration_evidence_digest)||r.successes>r.probes||r.failures>r.probes||r.successes+r.failures!=r.probes||static_cast<unsigned>(r.modality)>static_cast<unsigned>(Modality::custom)||r.state<RouteEvidenceState::declared||static_cast<unsigned>(r.state)>static_cast<unsigned>(RouteEvidenceState::qualified))return false;if(r.probes&& !digest(r.latest_probe_evidence_digest))return false;if(!r.probes&&!r.latest_probe_evidence_digest.empty())return false;if(r.state>=RouteEvidenceState::observed&&(!r.successes||!digest(r.latest_probe_evidence_digest)))return false;if(r.state!=RouteEvidenceState::qualified&&!r.qualification_evidence_digest.empty())return false;if(r.state==RouteEvidenceState::qualified&&(!digest(r.qualification_evidence_digest)||r.successes<policy_.minimum_successes||static_cast<double>(r.failures)/static_cast<double>(r.probes)>policy_.maximum_failure_rate))return false;}for(const auto&[id,o]:observations_){const auto r=routes_.find(o.route_id);if(id!=o.id||!text(o.id)||!text(o.route_id)||r==routes_.end()||r->second.state<RouteEvidenceState::observed||!digest(o.payload_digest)||!digest(o.provenance_digest)||o.received_at<o.captured_at||!ratio(o.confidence)||!ratio(o.uncertainty))return false;}for(const auto&[id,f]:features_)if(id!=f.id||!text(f.id)||!text(f.observation_id)||!text(f.name)||!digest(f.value_digest)||!digest(f.derivation_digest)||!ratio(f.confidence)||!ratio(f.uncertainty)||!observations_.contains(f.observation_id))return false;return true;}
}
