#include "genesis/memory/graph.hpp"
#include "genesis/runtime/runtime.hpp"
#include <algorithm>
#include <bit>
#include <cmath>
#include <set>
#include <stdexcept>

namespace genesis::memory { namespace {
bool text_ok(std::string_view s){return !s.empty()&&s.size()<=1024&&std::all_of(s.begin(),s.end(),[](unsigned char c){return c>=0x20&&c!=0x7f;});}
bool digest_ok(std::string_view s){return s.size()==64&&std::all_of(s.begin(),s.end(),[](unsigned char c){return std::isxdigit(c)!=0;});}
bool ratio(double v){return std::isfinite(v)&&v>=0&&v<=1;}
}
MemoryGraph::MemoryGraph(std::string id,std::size_t nc,std::size_t ec):organism_id_(std::move(id)),node_capacity_(nc),edge_capacity_(ec){if(!text_ok(organism_id_)||!nc||!ec)throw std::invalid_argument("invalid memory graph limits");}
bool MemoryGraph::add(MemoryNode n,std::string* e){if(e)e->clear(); auto fail=[&](const char*m){if(e)*e=m;return false;}; if(nodes_.size()>=node_capacity_)return fail("node capacity exceeded"); if(!text_ok(n.id)||nodes_.contains(n.id)||n.owner_id!=organism_id_||!digest_ok(n.content_digest)||!digest_ok(n.provenance_digest)||!ratio(n.confidence)||!ratio(n.strength)||!std::isfinite(n.affect_valence)||n.affect_valence < -1||n.affect_valence>1)return fail("invalid or duplicate memory"); std::set<std::string> unique; for(const auto& f:n.features)if(!text_ok(f)||!unique.insert(f).second)return fail("invalid features");const auto id=n.id;const auto context=n.context;const auto features=n.features;nodes_.emplace(id,std::move(n));for(const auto&f:features)feature_index_[f].insert(id);if(!context.empty())context_index_[context].insert(id);return true;}
bool MemoryGraph::connect(MemoryEdge x,std::string* e){if(e)e->clear();if(edges_.size()>=edge_capacity_||!nodes_.contains(x.from)||!nodes_.contains(x.to)||x.from==x.to||!text_ok(x.relation)||!std::isfinite(x.weight)||x.weight< -1||x.weight>1||std::any_of(edges_.begin(),edges_.end(),[&](const auto& y){return y.from==x.from&&y.to==x.to&&y.relation==x.relation;})){if(e)*e="invalid memory edge";return false;}const auto from=x.from;edges_.push_back(std::move(x));outgoing_edge_index_[from].push_back(edges_.size()-1);return true;}
std::vector<ActivatedMemory> MemoryGraph::activate(const std::vector<std::string>& f,std::string_view c,std::size_t max)const{std::set<std::string> candidates;for(const auto&q:f){const auto it=feature_index_.find(q);if(it!=feature_index_.end())candidates.insert(it->second.begin(),it->second.end());}if(!c.empty()){const auto it=context_index_.find(std::string(c));if(it!=context_index_.end())candidates.insert(it->second.begin(),it->second.end());}std::vector<ActivatedMemory> out;for(const auto&id:candidates){const auto&n=nodes_.at(id);if(n.state!=ActivationState::available)continue;std::size_t matches=0;for(const auto&q:f)if(std::find(n.features.begin(),n.features.end(),q)!=n.features.end())++matches;double score=(f.empty()?0.0:static_cast<double>(matches)/f.size())*.65+n.strength*.2+n.confidence*.1+(n.context==c?.05:0);if(score>0)out.push_back({id,score});}std::sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.score!=b.score?a.score>b.score:a.id<b.id;});if(out.size()>max)out.resize(max);return out;}
bool MemoryGraph::reinforce(std::string_view id,double amount,std::uint64_t now){auto it=nodes_.find(std::string(id));if(it==nodes_.end()||!std::isfinite(amount)||amount<0||it->second.state==ActivationState::hard_deleted)return false;it->second.strength=std::clamp(it->second.strength+amount,0.0,1.0);it->second.last_accessed=now;++it->second.access_count;if(it->second.state==ActivationState::dormant)it->second.state=ActivationState::available;return true;}
std::string MemoryGraph::state_digest(const MemoryNode&n){return runtime::sha256(n.id+"|"+std::to_string(std::bit_cast<std::uint64_t>(n.strength))+"|"+std::to_string(std::bit_cast<std::uint64_t>(n.confidence))+"|"+std::to_string(static_cast<unsigned>(n.state))+"|"+std::to_string(n.last_accessed)+"|"+std::to_string(n.access_count));}
bool MemoryGraph::reinforce_batch(const std::vector<ReinforcementRequest>& requests,std::uint64_t now,std::vector<ReinforcementChange>*changes,std::string*e){if(e)e->clear();if(changes)changes->clear();auto fail=[&](const char*m){if(e)*e=m;return false;};if(requests.empty())return fail("empty reinforcement batch");std::set<std::string> ids;struct Target{MemoryNode*live;MemoryNode before;MemoryNode after;};std::vector<Target> targets;targets.reserve(requests.size());std::vector<ReinforcementChange> applied;applied.reserve(requests.size());for(const auto&r:requests){auto it=nodes_.find(r.id);if(!text_ok(r.id)||!ids.insert(r.id).second||it==nodes_.end()||!std::isfinite(r.amount)||r.amount<=0||r.amount>1||it->second.state==ActivationState::hard_deleted||now<it->second.last_accessed||!digest_ok(r.expected_state_digest)||state_digest(it->second)!=r.expected_state_digest)return fail("invalid stale or unavailable reinforcement request");MemoryNode projected=it->second;projected.strength=std::clamp(projected.strength+r.amount,0.0,1.0);projected.last_accessed=now;++projected.access_count;if(projected.state==ActivationState::dormant)projected.state=ActivationState::available;applied.push_back({projected.id,state_digest(it->second),state_digest(projected),it->second.strength,projected.strength,it->second.state,projected.state});targets.push_back({&it->second,it->second,std::move(projected)});}for(auto&target:targets)std::swap(*target.live,target.after);if(!verify()){for(auto&target:targets)std::swap(*target.live,target.before);return fail("post-reinforcement invariant failure; batch rolled back");}if(changes)*changes=std::move(applied);return true;}
bool MemoryGraph::decay(double d,double p){if(!ratio(d)||!ratio(p))return false;for(auto&[_,n]:nodes_){if(n.state==ActivationState::hard_deleted)continue;const double rate=n.kind==MemoryKind::skill?p:d;n.strength=std::max(0.0,n.strength-rate);if(n.strength==0)n.state=ActivationState::archival;else if(n.strength<.2)n.state=ActivationState::dormant;}return true;}
bool MemoryGraph::consolidate(std::string_view id,std::string* e){auto it=nodes_.find(std::string(id));if(it==nodes_.end()||it->second.state==ActivationState::hard_deleted){if(e)*e="memory unavailable";return false;}it->second.strength=std::min(1.0,it->second.strength+.15);it->second.confidence=std::min(1.0,it->second.confidence+.05);it->second.state=ActivationState::available;return true;}
std::vector<OutcomePrediction> MemoryGraph::predict(const std::vector<std::string>& f,std::string_view c,std::size_t max)const{std::map<std::string,OutcomePrediction> grouped;for(const auto&a:activate(f,c,node_capacity_)){const auto& n=nodes_.at(a.id);if(n.kind!=MemoryKind::prediction&&n.kind!=MemoryKind::episode)continue;auto& p=grouped[n.context];p.outcome=n.context;p.probability+=a.score*n.confidence;p.confidence+=n.confidence;p.evidence_ids.push_back(n.id);}std::vector<OutcomePrediction> out;for(auto&[_,p]:grouped){p.probability=std::clamp(p.probability/static_cast<double>(p.evidence_ids.size()),0.0,1.0);p.confidence=std::clamp(p.confidence/static_cast<double>(p.evidence_ids.size()),0.0,1.0);out.push_back(std::move(p));}std::sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.probability>b.probability;});if(out.size()>max)out.resize(max);return out;}
std::vector<RelatedMemory> MemoryGraph::related(std::string_view start,std::string_view relation,std::size_t max_depth,std::size_t max_results)const{std::vector<RelatedMemory> out;if(!nodes_.contains(std::string(start))||!max_depth||!max_results)return out;struct Pending{std::string id;std::size_t depth;double weight;std::vector<std::string> relations;};std::vector<Pending> queue{{std::string(start),0,1.0,{}}};std::set<std::string> visited{std::string(start)};std::size_t cursor=0;while(cursor<queue.size()&&out.size()<max_results){auto current=std::move(queue[cursor++]);if(current.depth>=max_depth)continue;const auto indexed=outgoing_edge_index_.find(current.id);if(indexed==outgoing_edge_index_.end())continue;for(const auto edge_index:indexed->second){const auto&e=edges_[edge_index];if(!relation.empty()&&e.relation!=relation)continue;if(!visited.insert(e.to).second)continue;auto path=current.relations;path.push_back(e.relation);const auto weight=current.weight*e.weight;out.push_back({e.to,current.depth+1,weight,path});queue.push_back({e.to,current.depth+1,weight,std::move(path)});if(out.size()==max_results)break;}}return out;}
const MemoryNode* MemoryGraph::find(std::string_view id)const noexcept{auto it=nodes_.find(std::string(id));return it==nodes_.end()?nullptr:&it->second;}
const std::string& MemoryGraph::organism_id()const noexcept{return organism_id_;}
std::size_t MemoryGraph::node_capacity()const noexcept{return node_capacity_;}
std::size_t MemoryGraph::edge_capacity()const noexcept{return edge_capacity_;}
const std::map<std::string,MemoryNode>& MemoryGraph::nodes()const noexcept{return nodes_;}
const std::vector<MemoryEdge>& MemoryGraph::edges()const noexcept{return edges_;}
bool MemoryGraph::verify()const{if(nodes_.size()>node_capacity_||edges_.size()>edge_capacity_)return false;for(const auto&[id,n]:nodes_)if(id!=n.id||n.owner_id!=organism_id_||!digest_ok(n.content_digest)||!digest_ok(n.provenance_digest)||!ratio(n.confidence)||!ratio(n.strength))return false;for(const auto&e:edges_)if(!nodes_.contains(e.from)||!nodes_.contains(e.to)||e.from==e.to)return false;return true;}
std::size_t MemoryGraph::size()const noexcept{return nodes_.size();}
}
