#include "genesis/memory/graph.hpp"
#include <algorithm>
#include <cmath>
#include <set>
#include <stdexcept>

namespace genesis::memory { namespace {
bool text_ok(std::string_view s){return !s.empty()&&s.size()<=1024&&std::all_of(s.begin(),s.end(),[](unsigned char c){return c>=0x20&&c!=0x7f;});}
bool digest_ok(std::string_view s){return s.size()==64&&std::all_of(s.begin(),s.end(),[](unsigned char c){return std::isxdigit(c)!=0;});}
bool ratio(double v){return std::isfinite(v)&&v>=0&&v<=1;}
}
MemoryGraph::MemoryGraph(std::string id,std::size_t nc,std::size_t ec):organism_id_(std::move(id)),node_capacity_(nc),edge_capacity_(ec){if(!text_ok(organism_id_)||!nc||!ec)throw std::invalid_argument("invalid memory graph limits");}
bool MemoryGraph::add(MemoryNode n,std::string* e){if(e)e->clear(); auto fail=[&](const char*m){if(e)*e=m;return false;}; if(nodes_.size()>=node_capacity_)return fail("node capacity exceeded"); if(!text_ok(n.id)||nodes_.contains(n.id)||n.owner_id!=organism_id_||!digest_ok(n.content_digest)||!digest_ok(n.provenance_digest)||!ratio(n.confidence)||!ratio(n.strength)||!std::isfinite(n.affect_valence)||n.affect_valence < -1||n.affect_valence>1)return fail("invalid or duplicate memory"); std::set<std::string> unique; for(const auto& f:n.features)if(!text_ok(f)||!unique.insert(f).second)return fail("invalid features"); nodes_.emplace(n.id,std::move(n));return true;}
bool MemoryGraph::connect(MemoryEdge x,std::string* e){if(e)e->clear();if(edges_.size()>=edge_capacity_||!nodes_.contains(x.from)||!nodes_.contains(x.to)||x.from==x.to||!text_ok(x.relation)||!std::isfinite(x.weight)||x.weight< -1||x.weight>1||std::any_of(edges_.begin(),edges_.end(),[&](const auto& y){return y.from==x.from&&y.to==x.to&&y.relation==x.relation;})){if(e)*e="invalid memory edge";return false;}edges_.push_back(std::move(x));return true;}
std::vector<ActivatedMemory> MemoryGraph::activate(const std::vector<std::string>& f,std::string_view c,std::size_t max)const{std::vector<ActivatedMemory> out;for(const auto&[id,n]:nodes_){if(n.state!=ActivationState::available)continue;std::size_t matches=0;for(const auto& q:f)if(std::find(n.features.begin(),n.features.end(),q)!=n.features.end())++matches;double score=(f.empty()?0.0:static_cast<double>(matches)/f.size())*.65+n.strength*.2+n.confidence*.1+(n.context==c?.05:0);if(score>0)out.push_back({id,score});}std::sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.score!=b.score?a.score>b.score:a.id<b.id;});if(out.size()>max)out.resize(max);return out;}
bool MemoryGraph::reinforce(std::string_view id,double amount,std::uint64_t now){auto it=nodes_.find(std::string(id));if(it==nodes_.end()||!std::isfinite(amount)||amount<0||it->second.state==ActivationState::hard_deleted)return false;it->second.strength=std::clamp(it->second.strength+amount,0.0,1.0);it->second.last_accessed=now;++it->second.access_count;if(it->second.state==ActivationState::dormant)it->second.state=ActivationState::available;return true;}
bool MemoryGraph::decay(double d,double p){if(!ratio(d)||!ratio(p))return false;for(auto&[_,n]:nodes_){if(n.state==ActivationState::hard_deleted)continue;const double rate=n.kind==MemoryKind::skill?p:d;n.strength=std::max(0.0,n.strength-rate);if(n.strength==0)n.state=ActivationState::archival;else if(n.strength<.2)n.state=ActivationState::dormant;}return true;}
bool MemoryGraph::consolidate(std::string_view id,std::string* e){auto it=nodes_.find(std::string(id));if(it==nodes_.end()||it->second.state==ActivationState::hard_deleted){if(e)*e="memory unavailable";return false;}it->second.strength=std::min(1.0,it->second.strength+.15);it->second.confidence=std::min(1.0,it->second.confidence+.05);it->second.state=ActivationState::available;return true;}
std::vector<OutcomePrediction> MemoryGraph::predict(const std::vector<std::string>& f,std::string_view c,std::size_t max)const{std::map<std::string,OutcomePrediction> grouped;for(const auto&a:activate(f,c,node_capacity_)){const auto& n=nodes_.at(a.id);if(n.kind!=MemoryKind::prediction&&n.kind!=MemoryKind::episode)continue;auto& p=grouped[n.context];p.outcome=n.context;p.probability+=a.score*n.confidence;p.confidence+=n.confidence;p.evidence_ids.push_back(n.id);}std::vector<OutcomePrediction> out;for(auto&[_,p]:grouped){p.probability=std::clamp(p.probability/static_cast<double>(p.evidence_ids.size()),0.0,1.0);p.confidence=std::clamp(p.confidence/static_cast<double>(p.evidence_ids.size()),0.0,1.0);out.push_back(std::move(p));}std::sort(out.begin(),out.end(),[](const auto&a,const auto&b){return a.probability>b.probability;});if(out.size()>max)out.resize(max);return out;}
const MemoryNode* MemoryGraph::find(std::string_view id)const noexcept{auto it=nodes_.find(std::string(id));return it==nodes_.end()?nullptr:&it->second;}
bool MemoryGraph::verify()const{if(nodes_.size()>node_capacity_||edges_.size()>edge_capacity_)return false;for(const auto&[id,n]:nodes_)if(id!=n.id||n.owner_id!=organism_id_||!digest_ok(n.content_digest)||!digest_ok(n.provenance_digest)||!ratio(n.confidence)||!ratio(n.strength))return false;for(const auto&e:edges_)if(!nodes_.contains(e.from)||!nodes_.contains(e.to)||e.from==e.to)return false;return true;}
std::size_t MemoryGraph::size()const noexcept{return nodes_.size();}
}
