#include "genesis/memory/persistence.hpp"
#include "genesis/runtime/runtime.hpp"
#include <bit>
#include <cctype>
#include <fstream>
#include <iterator>
#include <stdexcept>
#include <system_error>
namespace genesis::memory { namespace {
constexpr std::string_view magic="GENESIS-MEMORY-V1"; constexpr std::uint64_t max_items=1000000,max_field=16U*1024U*1024U;
void err(MemoryStoreError*e,MemoryStoreErrorCode c,std::string m){if(e){e->code=c;e->message=std::move(m);}}
void id_ok(std::string_view s){if(s.empty()||s.size()>128||s=="."||s=="..")throw std::invalid_argument("unsafe identifier");for(unsigned char c:s)if(!std::isalnum(c)&&c!='_'&&c!='-'&&c!='.')throw std::invalid_argument("unsafe identifier character");}
void u64(std::string&o,std::uint64_t v){for(unsigned s=0;s<64;s+=8)o.push_back(static_cast<char>((v>>s)&255));}
std::uint64_t get64(std::string_view b,std::size_t&o){if(o>b.size()||b.size()-o<8)throw std::runtime_error("truncated integer");std::uint64_t v=0;for(unsigned s=0;s<64;s+=8)v|=static_cast<std::uint64_t>(static_cast<unsigned char>(b[o++]))<<s;return v;}
void str(std::string&o,std::string_view s){u64(o,s.size());o.append(s);}
std::string getstr(std::string_view b,std::size_t&o){auto n=get64(b,o);if(n>max_field||n>b.size()-o)throw std::runtime_error("invalid field length");std::string s(b.substr(o,n));o+=n;return s;}
void strings(std::string&o,const std::vector<std::string>&v){if(v.size()>max_items)throw std::invalid_argument("too many strings");u64(o,v.size());for(const auto&s:v)str(o,s);}
std::vector<std::string> getstrings(std::string_view b,std::size_t&o){auto n=get64(b,o);if(n>max_items)throw std::runtime_error("too many strings");std::vector<std::string>v;v.reserve(n);while(n--)v.push_back(getstr(b,o));return v;}
std::string readall(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("cannot open memory record");std::string b{std::istreambuf_iterator<char>(f),{}};if(f.bad())throw std::runtime_error("cannot read memory record");return b;}
}
MemoryStore::MemoryStore(std::filesystem::path r,std::size_t m):root_(std::move(r)),maximum_record_bytes_(m){if(root_.empty()||m<1024)throw std::invalid_argument("invalid memory store configuration");}
std::string MemoryStore::serialize(const MemoryGraph&g){if(!g.verify())throw std::invalid_argument("invalid memory graph");std::string o(magic);str(o,g.organism_id());u64(o,g.node_capacity());u64(o,g.edge_capacity());u64(o,g.nodes().size());for(const auto&[_,n]:g.nodes()){str(o,n.id);str(o,n.owner_id);str(o,n.content_digest);str(o,n.provenance_digest);str(o,n.context);u64(o,static_cast<std::uint64_t>(n.kind));u64(o,static_cast<std::uint64_t>(n.origin));u64(o,static_cast<std::uint64_t>(n.scope));u64(o,static_cast<std::uint64_t>(n.state));u64(o,std::bit_cast<std::uint64_t>(n.confidence));u64(o,std::bit_cast<std::uint64_t>(n.strength));u64(o,std::bit_cast<std::uint64_t>(n.affect_valence));u64(o,n.created_at);u64(o,n.last_accessed);u64(o,n.access_count);strings(o,n.features);}u64(o,g.edges().size());for(const auto&e:g.edges()){str(o,e.from);str(o,e.to);u64(o,std::bit_cast<std::uint64_t>(e.weight));str(o,e.relation);}o+=runtime::sha256(o);return o;}
std::optional<MemoryGraph> MemoryStore::deserialize(std::string_view b,MemoryStoreError*e){try{if(b.size()<magic.size()+64||b.substr(0,magic.size())!=magic)throw std::runtime_error("invalid memory magic");const auto payload=b.substr(0,b.size()-64);if(runtime::sha256(payload)!=b.substr(b.size()-64))throw std::runtime_error("memory checksum mismatch");std::size_t o=magic.size();auto owner=getstr(payload,o);auto nc=get64(payload,o),ec=get64(payload,o);if(!nc||!ec||nc>max_items||ec>max_items)throw std::runtime_error("invalid capacities");MemoryGraph g(owner,nc,ec);auto count=get64(payload,o);if(count>nc)throw std::runtime_error("node count exceeds capacity");while(count--){MemoryNode n;n.id=getstr(payload,o);n.owner_id=getstr(payload,o);n.content_digest=getstr(payload,o);n.provenance_digest=getstr(payload,o);n.context=getstr(payload,o);auto kind=get64(payload,o),origin=get64(payload,o),scope=get64(payload,o),state=get64(payload,o);if(kind>static_cast<std::uint64_t>(MemoryKind::prediction)||origin>static_cast<std::uint64_t>(Origin::external_source)||scope>static_cast<std::uint64_t>(IdentityScope::external_reference)||state>static_cast<std::uint64_t>(ActivationState::hard_deleted))throw std::runtime_error("invalid enum value");n.kind=static_cast<MemoryKind>(kind);n.origin=static_cast<Origin>(origin);n.scope=static_cast<IdentityScope>(scope);n.state=static_cast<ActivationState>(state);n.confidence=std::bit_cast<double>(get64(payload,o));n.strength=std::bit_cast<double>(get64(payload,o));n.affect_valence=std::bit_cast<double>(get64(payload,o));n.created_at=get64(payload,o);n.last_accessed=get64(payload,o);n.access_count=get64(payload,o);n.features=getstrings(payload,o);std::string reason;if(!g.add(std::move(n),&reason))throw std::runtime_error("invalid node: "+reason);}auto edges=get64(payload,o);if(edges>ec)throw std::runtime_error("edge count exceeds capacity");while(edges--){MemoryEdge x;x.from=getstr(payload,o);x.to=getstr(payload,o);x.weight=std::bit_cast<double>(get64(payload,o));x.relation=getstr(payload,o);std::string reason;if(!g.connect(std::move(x),&reason))throw std::runtime_error("invalid edge: "+reason);}if(o!=payload.size()||!g.verify())throw std::runtime_error("trailing or invalid memory data");err(e,MemoryStoreErrorCode::none,{});return g;}catch(const std::exception&x){err(e,MemoryStoreErrorCode::corrupt_record,x.what());return std::nullopt;}}
bool MemoryStore::write(const MemoryGraph&g,std::string_view v,MemoryStoreError*e)const{try{id_ok(g.organism_id());id_ok(v);auto b=serialize(g);if(b.size()>maximum_record_bytes_)throw std::invalid_argument("memory record exceeds configured limit");std::error_code ec;std::filesystem::create_directories(root_,ec);if(ec)throw std::runtime_error("cannot create memory store");auto target=root_/(g.organism_id()+"."+std::string(v)+".memory");if(std::filesystem::exists(target)){auto old=readall(target);if(old==b){err(e,MemoryStoreErrorCode::none,{});return true;}err(e,MemoryStoreErrorCode::conflicting_version,"immutable memory version conflict");return false;}auto tmp=std::filesystem::path(target.string()+".tmp-"+runtime::sha256(b));{std::ofstream f(tmp,std::ios::binary|std::ios::trunc);f.write(b.data(),static_cast<std::streamsize>(b.size()));f.flush();if(!f)throw std::runtime_error("cannot flush memory record");}std::filesystem::rename(tmp,target,ec);if(ec){std::filesystem::remove(tmp);throw std::runtime_error("cannot atomically commit memory record");}err(e,MemoryStoreErrorCode::none,{});return true;}catch(const std::invalid_argument&x){err(e,MemoryStoreErrorCode::invalid_graph,x.what());return false;}catch(const std::exception&x){err(e,MemoryStoreErrorCode::io_error,x.what());return false;}}
std::optional<MemoryGraph> MemoryStore::read(std::string_view owner,std::string_view v,MemoryStoreError*e)const{try{id_ok(owner);id_ok(v);auto p=root_/(std::string(owner)+"."+std::string(v)+".memory");if(!std::filesystem::exists(p)){err(e,MemoryStoreErrorCode::not_found,"memory record not found");return std::nullopt;}auto b=readall(p);if(b.size()>maximum_record_bytes_){err(e,MemoryStoreErrorCode::corrupt_record,"memory record exceeds configured limit");return std::nullopt;}auto g=deserialize(b,e);if(g&&g->organism_id()!=owner){err(e,MemoryStoreErrorCode::corrupt_record,"memory owner mismatch");return std::nullopt;}return g;}catch(const std::invalid_argument&x){err(e,MemoryStoreErrorCode::invalid_identifier,x.what());return std::nullopt;}catch(const std::exception&x){err(e,MemoryStoreErrorCode::io_error,x.what());return std::nullopt;}}
}
