#pragma once

// Stable public umbrella header. Implementations live in the compiled
// genesis_core library; clients can include narrower module headers instead.
#include "genesis/common/immutable_snapshot.hpp"
#include "genesis/common/text.hpp"
#include "genesis/cognition/workspace.hpp"
#include "genesis/cognition/persistence.hpp"
#include "genesis/cognition/world_model.hpp"
#include "genesis/cognition/world_persistence.hpp"
#include "genesis/development/maturity.hpp"
#include "genesis/genetics/expression.hpp"
#include "genesis/genetics/genome.hpp"
#include "genesis/genetics/persistence.hpp"
#include "genesis/genetics/reproduction.hpp"
#include "genesis/identity/entity_persistence.hpp"
#include "genesis/identity/entity_registry.hpp"
#include "genesis/identity/life_persistence.hpp"
#include "genesis/identity/life_record.hpp"
#include "genesis/identity/lineage.hpp"
#include "genesis/learning/consolidation.hpp"
#include "genesis/learning/persistence.hpp"
#include "genesis/memory/origin.hpp"
#include "genesis/memory/graph.hpp"
#include "genesis/memory/persistence.hpp"
#include "genesis/organism/anatomy.hpp"
#include "genesis/organism/systems.hpp"
#include "genesis/provenance/ledger.hpp"
#include "genesis/requirements/registry.hpp"
#include "genesis/runtime/runtime.hpp"
#include "genesis/security/crypto_provider.hpp"
#include "genesis/security/crypto_persistence.hpp"
#include "genesis/security/key_custody.hpp"
#include "genesis/security/key_custody_persistence.hpp"
#include "genesis/security/platform_crypto_inventory.hpp"
